#!/usr/bin/env python3
"""Build full_corpus_audit.csv — the single CSV the user audits in.

Combines:
  - full_corpus_cleaned.csv (cleaned identity, paths, modifier, all facets)
  - full_corpus_enriched.csv (FNDDS / SR28 / ESHA codes assigned per SKU)
  - MainFoodDesc16.csv         → FNDDS code → description
  - FNDDSSRLinks.csv           → SR code  → description
  - esha_cleaned.csv           → ESHA code → description

Output columns are the cleaned-CSV columns + retail_leaf_path/modifier from
enriched + the three reference codes + their descriptions, so a human auditor
can read each row and immediately see what FNDDS/SR28/ESHA the SKU was matched
to without separate lookups.

Usage:
    python3 retail_mapper/v2/build_audit_csv.py
"""
from __future__ import annotations

import csv
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
V2 = REPO / "retail_mapper" / "v2"
CLEANED = V2 / "full_corpus_cleaned.csv"
ENRICHED = V2 / "full_corpus_enriched.csv"
# Hestia's MainFoodDesc.csv uses the short codes that match the canonical tree's
# `fndds_code` outputs. Fall back to MainFoodDesc16 (FNDDS 2015-16 8-digit codes)
# for any codes not present in the Hestia file.
FNDDS_FILE_HESTIA = REPO.parent / "Hestia" / "api" / "data" / "MainFoodDesc.csv"
FNDDS_FILE_2016   = REPO / "data" / "fndds" / "MainFoodDesc16.csv"
# Full SR28 — NDB_number → fdc_id (via sr_legacy_food.csv) → description (via food.csv).
# The bridge file FNDDSSRLinks only has SR codes that link to FNDDS dietary
# survey data (~3,101). The full SR28 has 7,793 entries including baby food.
SR_LEGACY = REPO / "data" / "sr28_csv" / "sr_legacy_food.csv"
SR_FOOD   = REPO / "data" / "sr28_csv" / "food.csv"
SR_LINKS  = REPO / "data" / "fndds" / "FNDDSSRLinks.csv"  # fallback only
ESHA_FILE = REPO / "esha_cleaned.csv"
OUT = V2 / "full_corpus_audit.csv"

csv.field_size_limit(sys.maxsize)

sys.path.insert(0, str(V2))
from taxonomy_finalizer import apply_finalized_taxonomy  # noqa: E402

# FNDDS-driven canonical overrides. When a row has an fndds_code listed in
# this map, force its canonical_path/product_identity_fixed to the values
# below — overrides anything cleanup or the LLM produced. Generated by
# build_fndds_canonical_map.py from the audit's FNDDS clusters.
try:
    sys.path.insert(0, str(V2))
    from fndds_canonical_map import (
        FNDDS_CANONICAL_PATH_MAP,
        FNDDS_CANONICAL_IDENTITY_MAP,
    )
    print(f"  loaded FNDDS canonical map: {len(FNDDS_CANONICAL_PATH_MAP):,} entries")
except ImportError:
    FNDDS_CANONICAL_PATH_MAP = {}
    FNDDS_CANONICAL_IDENTITY_MAP = {}
    print("  WARN: fndds_canonical_map.py not found — skipping FNDDS overrides")

try:
    from path_rewrite_map import PATH_REWRITE
    print(f"  loaded path rewrite map: {len(PATH_REWRITE):,} entries")
except ImportError:
    PATH_REWRITE = {}
    print("  WARN: path_rewrite_map.py not found — skipping path rewrites")

try:
    from path_normalizer import normalize_path
    print(f"  loaded path normalizer (Top-Down family configs)")
    _NORMALIZER_LOADED = True
except ImportError as e:
    _NORMALIZER_LOADED = False
    print(f"  WARN: path_normalizer not available — skipping normalize ({e})")

# DeepSeek FNDDS corrections — adopted FNDDS code per fdc_id, with new
# fndds_desc. Applied at the very start of the row-processing loop so the
# corrected code flows through FNDDS_CANONICAL_PATH_MAP, the title-veto guard,
# the path normalizer, and the path-rewrite map exactly like a fresh code.
FNDDS_CORRECTIONS: dict[str, tuple[str, str]] = {}
_corrections_path = V2 / "fndds_corrections.csv"
if _corrections_path.exists():
    with _corrections_path.open(encoding="utf-8") as _fh:
        for _r in csv.DictReader(_fh):
            _fdc = (_r.get("fdc_id") or "").strip()
            _new_code = (_r.get("new_code") or "").strip()
            _new_desc = (_r.get("new_desc") or "").strip()
            if _fdc and _new_code:
                FNDDS_CORRECTIONS[_fdc] = (_new_code, _new_desc)
    print(f"  loaded FNDDS corrections: {len(FNDDS_CORRECTIONS):,} entries")
else:
    print(f"  no fndds_corrections.csv yet — running without DeepSeek corrections")

# Hand-curated overrides for FNDDS-canonical-map entries that are demonstrably
# wrong (built from old / sparse audit data). Applied IN PLACE of the auto-
# generated FNDDS_CANONICAL_PATH_MAP entry — the override wins. Add codes here
# when DeepSeek surfaces a real food category that the map hasn't caught up to.
FNDDS_PATH_OVERRIDES: dict[str, str] = {
    # Cookie-family FNDDS codes wrongly mapped by auto-generated map.
    # All cookies belong at Snack > Cookies; title-driven normalizer
    # adds sub-categories (chocolate chip, oatmeal, etc.).
    "53201000": "Snack > Cookies",                 # Cookie, NFS
    "53206000": "Snack > Cookies",                 # Cookie, chocolate chip
    "53206030": "Snack > Cookies",                 # Cookie, chocolate chip, reduced fat
    "53241500": "Snack > Cookies",                 # Cookie, butter or sugar
    "53225000": "Snack > Cookies",                 # Cookie, macaroon (coconut cookie, not candy)
    "53223100": "Snack > Cookies",                 # Cookie, granola (granola cookies are cookies)
    # Bagel codes — sometimes auto-map writes Bakery > Bread
    "51180030": "Bakery > Bagels",                 # bagel with raisins
    "51180000": "Bakery > Bagels",                 # bagel
    "51180010": "Bakery > Bagels",                 # bagel, plain
    "51180020": "Bakery > Bagels",                 # bagel, whole grain
    # Sushi codes
    "58151180": "Meal > Sushi",                    # sushi roll
    "58151190": "Meal > Sushi",                    # sushi
    "58151000": "Meal > Sushi",                    # nigiri
    "58151100": "Meal > Sushi",                    # sashimi
    # Beignet
    "53520510": "Bakery > Beignets",               # beignet
    # Note: 53203500 (biscotti) → Bakery > Biscotti is correct
    # Note: 53204000/53204010 (brownie cookies) → Bakery > Brownies is fine
    # Note: 53251100 (rugelach) → Bakery > Pastry is fine
    # Note: 53242500 (toffee bar) — borderline; keep auto-mapping for now
}
FNDDS_IDENTITY_OVERRIDES: dict[str, str] = {
    "53201000": "Cookie",
    "53206000": "Chocolate Chip Cookie",
    "53206030": "Chocolate Chip Cookie",
    "53241500": "Butter Cookie",
    "53225000": "Macaroon",
    "53223100": "Granola Cookie",
    # Bagels
    "51180030": "Bagels",
    "51180000": "Bagels",
    "51180010": "Bagels",
    "51180020": "Bagels",
    # Sushi
    "58151180": "Sushi Roll",
    "58151190": "Sushi",
    "58151000": "Nigiri",
    "58151100": "Sashimi",
    # Beignet
    "53520510": "Beignets",
}

# DeepSeek path-describe corrections — Pass 2 of the two-pass design.
# fdc_id -> canonical_path. When present, adopts this path as the final
# canonical_path, overriding the FNDDS-canonical-map + normalizer chain.
PATH_DESCRIBE_CORRECTIONS: dict[str, str] = {}
_pd_path = V2 / "path_describe_corrections.csv"
if _pd_path.exists():
    with _pd_path.open(encoding="utf-8") as _fh:
        for _r in csv.DictReader(_fh):
            _fdc = (_r.get("fdc_id") or "").strip()
            _new = (_r.get("new_path") or "").strip()
            if _fdc and _new:
                PATH_DESCRIBE_CORRECTIONS[_fdc] = _new
    print(f"  loaded path-describe corrections: {len(PATH_DESCRIBE_CORRECTIONS):,} entries")
else:
    print(f"  no path_describe_corrections.csv yet — running without two-pass overrides")

# Title-blocker veto for FNDDS canonical-path override.
# Matcher sometimes mis-assigns FNDDS codes (Honey Hamburger Buns → fndds
# "honey bun"; fresh apples → fndds "apple crisp cake mix"). When the title
# clearly contradicts the FNDDS-canonical-path target, skip the override and
# let the row keep whatever path the cleanup pipeline produced.
# Title-required guards — positive evidence rule.
# When a path is in this map, the FNDDS canonical-path override only applies
# if the product title contains at least one of the listed signal words.
# This stops matcher errors from cascading: if the matcher mis-assigned an
# FNDDS code (e.g., a fresh apple → "apple crisp cake mix" FNDDS), the
# resulting force-route to Cake Mix gets vetoed because the title doesn't
# contain "cake".
PATH_TITLE_REQUIRED: dict[str, set[str]] = {
    "Pantry > Baking Mixes > Cake Mix":
        {"cake", "torte", "gateau"},
    "Pantry > Baking Mixes > Pancake Mix":
        {"pancake", "flapjack", "hotcake"},
    "Pantry > Baking Mixes > Waffle Mix":
        {"waffle"},
    "Pantry > Baking Mixes > Brownie Mix":
        {"brownie"},
    "Pantry > Baking Mixes > Cookie Mix":
        {"cookie"},
    "Pantry > Baking Mixes > Muffin Mix":
        {"muffin"},
    "Pantry > Baking Mixes > Biscuit Mix":
        {"biscuit"},
    "Pantry > Baking Mixes > Bread Mix":
        {"bread"},
    "Pantry > Baking Mixes > Doughnut Mix":
        {"donut", "doughnut"},
    "Pantry > Baking Mixes > Scone Mix":
        {"scone"},
    "Pantry > Baking Mixes > Dough Mix":
        {"dough"},
    "Pantry > Baking Mixes":
        {"baking", "mix"},
    "Bakery > Snack Cakes > Honey Buns":
        {"honey bun", "honeybun"},
    "Bakery > Snack Cakes > Twinkies":
        {"twinkie"},
    "Bakery > Snack Cakes > Ho Hos":
        {"ho ho", "hoho"},
    "Bakery > Snack Cakes > Ding Dongs":
        {"ding dong", "dingdong"},
    "Bakery > Snack Cakes > Zingers":
        {"zinger"},
    "Bakery > Doughnuts":
        {"donut", "doughnut", "cruller", "pczki", "paczki", "bismarck",
         "fastnacht", "fasnacht", "donout", "long john", "bear claw"},
    "Bakery > English Muffins":
        {"english muffin"},
    "Bakery > Croutons":
        {"crouton", "grouton", "crounton", "croton"},
    "Bakery > Biscotti":
        {"biscotti", "cantuccini"},
    "Bakery > Pastry > Churros":
        {"churro"},
    "Bakery > Pastry > Danishes":
        {"danish"},
    "Bakery > Pastry > Croissants":
        {"croissant"},
    "Bakery > Pastry > Eclairs":
        {"eclair"},
    "Bakery > Bagels":
        {"bagel"},
    "Bakery > Naan":
        {"naan"},
    "Bakery > Pita Bread":
        {"pita"},
    "Bakery > Tortillas":
        {"tortilla"},
    "Bakery > Flatbread":
        {"flatbread", "flat bread"},
    "Bakery > Cornbread":
        {"cornbread", "corn bread"},
    "Bakery > Brownies":
        {"brownie"},
    "Bakery > Scones":
        {"scone"},
    "Meat & Seafood > Crab > Crab Cakes":
        {"crab cake", "crab patty", "cr'b cake", "crabcake"},
    "Meat & Seafood > Seafood > Fish Cakes":
        {"fish cake", "fishcake"},
    "Meat & Seafood > Salmon > Salmon Cakes":
        {"salmon cake", "salmon patty"},
    "Frozen > Ice Cream":
        {"ice cream", "icecream", "gelato", "frozen dessert", "dairy dessert",
         "frzn", "frz ", "frozen yogurt-style", "non-dairy frozen",
         "sorbet", "sherbet", "soy cream", "oat cream", "cashew cream",
         "coconut cream frozen", "frozen treat"},
    "Frozen > Frozen Yogurt":
        {"frozen yogurt", "froyo"},
    "Beverage > Plant Milk > Almond Milk":
        {"almond"},
    "Beverage > Plant Milk > Oat Milk":
        {"oat"},
    "Beverage > Plant Milk > Soy Milk":
        {"soy"},
    "Beverage > Plant Milk > Coconut Milk":
        {"coconut"},
    "Beverage > Plant Milk > Rice Milk":
        {"rice"},
    "Dairy > Yogurt > Greek Yogurt":
        {"greek"},
    "Pantry > Dips & Spreads > Hummus":
        {"hummus"},
    "Meal > Pasta Dishes > Mac and Cheese":
        {"mac", "macaroni"},
    "Meal > Pasta Dishes > Lasagna":
        {"lasagna", "lasagne"},
    "Pantry > Pasta > Spaghetti":
        {"spaghetti"},
    "Baby & Toddler > Baby Food":
        {"baby", "infant", "toddler", "stage"},
    "Baby & Toddler > Infant Formula":
        {"formula"},
}


def title_blocked(target_path: str, title: str) -> bool:
    """Return True if FNDDS override should be vetoed for this title.
    Veto fires when path requires a title signal and none is present.
    """
    required = PATH_TITLE_REQUIRED.get(target_path)
    if required is None:
        return False
    tlow = title.lower()
    return not any(kw in tlow for kw in required)


# Cheese-type splitter: FNDDS lumps most cheeses into a flat "Dairy > Cheese"
# bucket, leaving 20K+ SKUs with no type-level breakout. Detect the cheese
# type from the title, and add an age/style sub-level when present.
# Order matters — most-specific match wins.
CHEESE_TYPES: list[tuple[str, str]] = [
    # Multi-word types first
    ("cream cheese",        "Cream Cheese"),
    ("cottage cheese",      "Cottage Cheese"),
    ("goat cheese",         "Goat Cheese"),
    ("blue cheese",         "Blue Cheese"),
    ("string cheese",       "String Cheese"),
    ("cheese stick",        "String Cheese"),
    ("pepper jack",         "Pepper Jack"),
    ("monterey jack",       "Monterey Jack"),
    ("colby jack",          "Colby Jack"),
    ("queso fresco",        "Queso Fresco"),
    ("queso blanco",        "Queso Blanco"),
    ("queso quesadilla",    "Queso Quesadilla"),
    ("cojita",              "Cotija"),
    ("cotija",              "Cotija"),
    ("oaxaca",              "Oaxaca"),
    ("parmigiano",          "Parmesan"),
    ("parmesan",            "Parmesan"),
    ("romano",              "Romano"),
    ("asiago",              "Asiago"),
    # Single-word types (after multi-word checks)
    ("cheddar",             "Cheddar"),
    ("mozzarella",          "Mozzarella"),
    ("provolone",           "Provolone"),
    ("swiss",               "Swiss"),
    ("gouda",               "Gouda"),
    ("feta",                "Feta"),
    ("brie",                "Brie"),
    ("camembert",           "Camembert"),
    ("ricotta",             "Ricotta"),
    ("american",            "American"),
    ("colby",               "Colby"),
    ("muenster",            "Muenster"),
    ("munster",             "Muenster"),
    ("havarti",             "Havarti"),
    ("manchego",            "Manchego"),
    ("halloumi",            "Halloumi"),
    ("mascarpone",          "Mascarpone"),
    ("gorgonzola",          "Gorgonzola"),
    ("roquefort",           "Roquefort"),
    ("stilton",             "Stilton"),
    ("limburger",           "Limburger"),
    ("burrata",             "Burrata"),
    ("fontina",             "Fontina"),
    ("gruyere",             "Gruyère"),
    ("gruyère",             "Gruyère"),
    ("emmentaler",          "Emmental"),
    ("emmental",            "Emmental"),
    ("paneer",              "Paneer"),
    ("queso",               "Queso"),
    ("jack",                "Jack"),
]

# Age/style modifier sub-level. Only applied AFTER a cheese type is matched.
CHEESE_MODIFIERS: list[tuple[str, str]] = [
    ("extra sharp",         "Extra Sharp"),
    ("extra-sharp",         "Extra Sharp"),
    ("extra mild",          "Extra Mild"),
    ("extra-mild",          "Extra Mild"),
    ("sharp",               "Sharp"),
    ("mild",                "Mild"),
    ("medium",              "Medium"),
    ("aged",                "Aged"),
    ("vintage",             "Vintage"),
    ("smoked",              "Smoked"),
    ("white",               "White"),
    ("yellow",              "Yellow"),
    ("low moisture",        "Low Moisture"),
    ("part skim",           "Part Skim"),
    ("part-skim",           "Part Skim"),
    ("whole milk",          "Whole Milk"),
    ("fresh",               "Fresh"),
]


def cheese_subpath(title: str) -> tuple[str, str | None] | None:
    """If title implies a cheese type, return (type_name, optional_modifier).
    Returns None if no cheese type matched."""
    tlow = title.lower()
    cheese_type = None
    for kw, type_name in CHEESE_TYPES:
        if kw in tlow:
            cheese_type = type_name
            break
    if not cheese_type:
        return None
    modifier = None
    for kw, mod_name in CHEESE_MODIFIERS:
        if kw in tlow:
            modifier = mod_name
            break
    return cheese_type, modifier


def reroute_cheese(canonical_path: str, title: str) -> str:
    """When a row sits at the flat 'Dairy > Cheese' bucket and the title
    implies a specific type, push it down into a type subcategory (and
    optional age/style child).
    """
    if canonical_path != "Dairy > Cheese":
        return canonical_path
    sub = cheese_subpath(title)
    if not sub:
        return canonical_path
    cheese_type, modifier = sub
    if modifier:
        return f"Dairy > Cheese > {cheese_type} > {modifier}"
    return f"Dairy > Cheese > {cheese_type}"


def load_fndds_desc() -> dict[str, str]:
    """Hestia's MainFoodDesc.csv first (short codes the canonical tree emits),
    then MainFoodDesc16 (FNDDS 2015-16 long codes) for anything missing."""
    out: dict[str, str] = {}
    if FNDDS_FILE_HESTIA.exists():
        with FNDDS_FILE_HESTIA.open(encoding="utf-8", errors="replace") as fh:
            for r in csv.DictReader(fh):
                code = (r.get("Food code") or "").strip()
                desc = (r.get("Main food description") or "").strip()
                if code and desc and code not in out:
                    out[code] = desc
    if FNDDS_FILE_2016.exists():
        with FNDDS_FILE_2016.open(encoding="utf-8", errors="replace") as fh:
            for r in csv.DictReader(fh):
                code = (r.get("Food code") or "").strip()
                desc = (r.get("Main food description") or "").strip()
                if code and desc and code not in out:
                    out[code] = desc
    return out


def load_sr28_desc() -> dict[str, str]:
    """Build NDB_number → description from the full SR28 reference (7,793 codes,
    includes 236 baby food entries). Falls back to FNDDSSRLinks for any missing."""
    out: dict[str, str] = {}
    if SR_LEGACY.exists() and SR_FOOD.exists():
        ndb_to_fdc: dict[str, str] = {}
        with SR_LEGACY.open(encoding="utf-8", errors="replace") as fh:
            for r in csv.DictReader(fh):
                ndb = (r.get("NDB_number") or "").strip()
                fdc = (r.get("fdc_id") or "").strip()
                if ndb and fdc:
                    ndb_to_fdc[ndb] = fdc
        fdc_to_desc: dict[str, str] = {}
        with SR_FOOD.open(encoding="utf-8", errors="replace") as fh:
            for r in csv.DictReader(fh):
                fdc = (r.get("fdc_id") or "").strip()
                d = (r.get("description") or "").strip()
                if fdc and d:
                    fdc_to_desc[fdc] = d
        for ndb, fdc in ndb_to_fdc.items():
            d = fdc_to_desc.get(fdc)
            if d:
                out[ndb] = d
    if SR_LINKS.exists():
        with SR_LINKS.open(encoding="utf-8", errors="replace") as fh:
            for r in csv.DictReader(fh):
                code = (r.get("SR code") or "").strip()
                desc = (r.get("SR description") or "").strip()
                if code and desc and code not in out:
                    out[code] = desc
    return out


def load_esha_desc() -> dict[str, str]:
    out: dict[str, str] = {}
    if not ESHA_FILE.exists():
        return out
    with ESHA_FILE.open(encoding="utf-8") as fh:
        for r in csv.DictReader(fh):
            code = (r.get("EshaCode") or "").strip()
            desc = (r.get("Description") or "").strip()
            if code and desc:
                out[code] = desc
    return out


def main() -> None:
    print("  loading reference description tables...")
    fndds_desc = load_fndds_desc()
    sr_desc = load_sr28_desc()
    esha_desc = load_esha_desc()
    print(f"    FNDDS:  {len(fndds_desc):,}")
    print(f"    SR28:   {len(sr_desc):,}")
    print(f"    ESHA:   {len(esha_desc):,}")

    # Index codes from enriched CSV by fdc_id (for fast lookup while streaming cleaned)
    print(f"  indexing {ENRICHED.name}...")
    enriched_by_fdc: dict[str, dict] = {}
    with ENRICHED.open(encoding="utf-8") as fh:
        for r in csv.DictReader(fh):
            fdc = (r.get("fdc_id") or "").strip()
            if fdc:
                enriched_by_fdc[fdc] = {
                    "modifier":         r.get("modifier", ""),
                    "retail_leaf_path": r.get("retail_leaf_path", ""),
                    "fndds_code":       r.get("fndds_code", ""),
                    "sr28_code":        r.get("sr28_code", ""),
                    "esha_code":        r.get("esha_code", ""),
                    "match_source":     r.get("match_source", ""),
                    "match_score":      r.get("match_score", ""),
                    "matched_key":      r.get("matched_key", ""),
                    "portions_json":    r.get("portions_json", ""),
                }
    print(f"    indexed {len(enriched_by_fdc):,} fdc_ids")

    # Stream cleaned CSV, augment, write audit CSV
    print(f"  reading {CLEANED.name} → writing {OUT.name}")
    n = 0
    with CLEANED.open(encoding="utf-8") as src, \
         OUT.open("w", encoding="utf-8", newline="") as dst:
        rdr = csv.DictReader(src)
        # Output columns: cleaned columns + enriched codes + descriptions
        cleaned_cols = list(rdr.fieldnames or [])
        extra_cols = [
            "modifier", "retail_leaf_path",
            "fndds_code", "fndds_desc",
            "sr28_code", "sr28_desc",
            "esha_code", "esha_desc",
            "match_source", "match_score", "matched_key", "portions_json",
        ]
        out_cols = cleaned_cols + [c for c in extra_cols if c not in cleaned_cols]
        wtr = csv.DictWriter(dst, fieldnames=out_cols)
        wtr.writeheader()
        n_fndds_path_override = 0
        n_fndds_id_override = 0
        n_fndds_vetoed = 0
        n_cheese_split = 0
        n_path_rewrite = 0
        n_normalized = 0
        n_fndds_corrected = 0
        n_path_describe = 0
        for row in rdr:
            fdc = (row.get("fdc_id") or "").strip()
            source_category_path = row.get("category_path_fixed", "")
            source_identity = row.get("product_identity_fixed", "")
            source_canonical_path = row.get("canonical_path", "")
            extra = enriched_by_fdc.get(fdc, {})
            f_code = extra.get("fndds_code", "")
            s_code = extra.get("sr28_code", "")
            e_code = extra.get("esha_code", "")
            # Apply DeepSeek FNDDS correction (if any) before any downstream
            # use of f_code. The corrected code feeds the canonical-path map,
            # title-veto, normalizer, and path-rewrite exactly like a fresh
            # matcher result.
            corr = FNDDS_CORRECTIONS.get(fdc)
            if corr:
                f_code = corr[0]
                n_fndds_corrected += 1
            row["modifier"]         = extra.get("modifier", "")
            row["retail_leaf_path"] = extra.get("retail_leaf_path", "")
            row["fndds_code"]       = f_code
            # Prefer corrected desc if provided, else look up from main lookup.
            row["fndds_desc"]       = (corr[1] if corr and corr[1]
                                       else (fndds_desc.get(f_code, "") if f_code else ""))
            row["sr28_code"]        = s_code
            row["sr28_desc"]        = sr_desc.get(s_code, "") if s_code else ""
            row["esha_code"]        = e_code
            row["esha_desc"]        = esha_desc.get(e_code, "") if e_code else ""
            row["match_source"]     = extra.get("match_source", "")
            row["match_score"]      = extra.get("match_score", "")
            row["matched_key"]      = extra.get("matched_key", "")
            row["portions_json"]    = extra.get("portions_json", "")
            # FNDDS-driven canonical override — keyed by fndds_code, ground
            # truth from the cluster audit. Forces SKUs that share an FNDDS
            # code to land at the same canonical_path/identity.
            if f_code:
                # Hand-override map wins over auto-generated FNDDS map.
                canon_path = FNDDS_PATH_OVERRIDES.get(f_code) or FNDDS_CANONICAL_PATH_MAP.get(f_code)
                title_now = row.get("title", "") or ""
                vetoed = canon_path and title_blocked(canon_path, title_now)
                if canon_path and not vetoed and row.get("canonical_path") != canon_path:
                    row["canonical_path"] = canon_path
                    n_fndds_path_override += 1
                if vetoed:
                    n_fndds_vetoed += 1
                canon_id = FNDDS_IDENTITY_OVERRIDES.get(f_code) or FNDDS_CANONICAL_IDENTITY_MAP.get(f_code)
                if canon_id and not vetoed and row.get("product_identity_fixed") != canon_id:
                    row["product_identity_fixed"] = canon_id
                    n_fndds_id_override += 1
            # Cheese type/age sub-router — legacy single-modifier router
            # (now superseded by path_normalizer for any family with a config,
            # but kept as fallback for paths that don't match a config).
            cur = row.get("canonical_path", "")
            new_cheese = reroute_cheese(cur, row.get("title", "") or "")
            if new_cheese != cur:
                row["canonical_path"] = new_cheese
                n_cheese_split += 1
            # Path-quality rewrite — applied BEFORE the normalizer so the
            # rewrite map handles word-order swaps and comma-leaves first.
            new_path = PATH_REWRITE.get(row.get("canonical_path", ""))
            if new_path:
                row["canonical_path"] = new_path
                n_path_rewrite += 1
            # Top-down structural normalizer — chains all applicable tier
            # modifiers (e.g., Mozzarella > Low Moisture > Part Skim) and
            # appends form + alphabetized claims from facet columns.
            if _NORMALIZER_LOADED:
                cur = row.get("canonical_path", "")
                normalized = normalize_path(
                    canonical_path=cur,
                    title=row.get("title", "") or "",
                    form_facet=row.get("form_texture_cut", "") or "",
                    claims_facet=row.get("claims", "") or "",
                )
                if normalized != cur:
                    row["canonical_path"] = normalized
                    n_normalized += 1
            # DeepSeek path-describe correction — final overlay. When the
            # full evidence-based two-pass LLM picked a specific canonical
            # path for this SKU, adopt it. Trumps the canonical-map +
            # normalizer chain.
            pd = PATH_DESCRIBE_CORRECTIONS.get(fdc)
            if pd:
                row["canonical_path"] = pd
                n_path_describe += 1
            # The audit file is a synchronized view, not an independent path
            # mutation target. Legacy FNDDS/path/LLM overlays above are retained
            # for counters while we stabilize the pipeline, but taxonomy columns
            # are finalized from the cleaned category+identity contract.
            row["category_path_fixed"] = source_category_path
            row["product_identity_fixed"] = source_identity
            row["canonical_path"] = source_canonical_path
            apply_finalized_taxonomy(row)
            wtr.writerow(row)
            n += 1
            if n % 100000 == 0:
                print(f"    {n:,} rows", flush=True)
        print(f"    FNDDS path overrides:     {n_fndds_path_override:,}")
        print(f"    FNDDS identity overrides: {n_fndds_id_override:,}")
        print(f"    FNDDS vetoed by title:    {n_fndds_vetoed:,}")
        print(f"    Cheese type/age split:    {n_cheese_split:,}")
        print(f"    Path-rewrite applied:     {n_path_rewrite:,}")
        print(f"    Path normalizer applied:  {n_normalized:,}")
        print(f"    DeepSeek FNDDS corrected: {n_fndds_corrected:,}")
        print(f"    DeepSeek path applied:    {n_path_describe:,}")

    print(f"  wrote {n:,} rows -> {OUT.name} ({OUT.stat().st_size / 1024 / 1024:.1f} MB)")
    # Quick coverage stats
    with OUT.open(encoding="utf-8") as fh:
        rdr = csv.DictReader(fh)
        n_with_fd = n_with_sr = n_with_es = 0
        for r in rdr:
            if r["fndds_desc"]: n_with_fd += 1
            if r["sr28_desc"]:  n_with_sr += 1
            if r["esha_desc"]:  n_with_es += 1
    print(f"    rows with FNDDS desc: {n_with_fd:,} ({100*n_with_fd/max(n,1):.0f}%)")
    print(f"    rows with SR28 desc:  {n_with_sr:,} ({100*n_with_sr/max(n,1):.0f}%)")
    print(f"    rows with ESHA desc:  {n_with_es:,} ({100*n_with_es/max(n,1):.0f}%)")

    # Seed PLU produce stubs from the IFPS list — appended after build so
    # every pipeline run preserves them. Idempotent: skips PLUs already
    # present in the audit (re-runs are safe).
    try:
        import seed_plu_into_master_db as plu_seed  # type: ignore
        print()
        print("  seeding IFPS PLU produce stubs...")
        plu_seed.main()
    except Exception as e:
        print(f"  WARN: PLU seed step failed: {e}")


if __name__ == "__main__":
    main()
