#!/usr/bin/env python3
"""Build a (product_identity_fixed) -> dominant FDC canonical_path map.

Mirrors build_fndds_canonical_map.py but keys on `product_identity_fixed`
instead of FNDDS code. The product_identity_fixed column is the LLM's primary
identity signal across every corpus (FDC retail audit, Walmart/Kroger,
recipe ingredients, SR28/FNDDS). When an identity has a clear dominant
canonical_path in FDC, force every row with that identity to that path —
this stops the fuzzy matcher from snapping correctly-identified rows to
junk paths created by lone misclassified FDC entries (e.g. "Bagels" being
routed to `Produce > Vegetables > Bagels` because of one misfiled FDC row).

Trust threshold: dominant path covers ≥60% of SKUs with that identity
(or ≥85% if paths span multiple top-level groups, which usually signals a
legitimate form-diff like fresh vs frozen vs canned).

Outputs retail_mapper/v2/product_identity_canonical_map.py — a Python module
with PRODUCT_IDENTITY_CANONICAL_PATH_MAP dict, ready to import.
"""
from __future__ import annotations

import csv
import os
import sys
from collections import Counter, defaultdict
from pathlib import Path

csv.field_size_limit(sys.maxsize)

REPO = Path(__file__).resolve().parents[2]
V2 = REPO / "retail_mapper" / "v2"
SRC = Path(os.environ.get("AUDIT_CSV") or (V2 / "consensus_full_corpus_audit.csv"))
OUT = V2 / "product_identity_canonical_map.py"

DOMINANCE_THRESHOLD = 0.60
DOMINANCE_CROSS_TOPLEVEL = 0.85
MIN_SKUS = 3


def main() -> int:
    if not SRC.exists():
        print(f"missing {SRC}", file=sys.stderr)
        return 2

    # identity -> Counter(canonical_path)
    paths_by_id: defaultdict[str, Counter[str]] = defaultdict(Counter)
    n_rows = 0
    with SRC.open() as f:
        for row in csv.DictReader(f):
            # Skip synthetic anchor rows — they only have one row each so they'd
            # always be 100% dominant for their own (degenerate) identity.
            if (row.get("consensus_source") or "").strip() == "synthetic_taxonomy_anchor":
                continue
            pid = (row.get("product_identity_fixed") or "").strip()
            cp = (row.get("canonical_path") or "").strip()
            if not pid or not cp:
                continue
            paths_by_id[pid][cp] += 1
            n_rows += 1

    print(f"scanned {n_rows:,} FDC rows", file=sys.stderr)
    print(f"distinct product_identity_fixed values: {len(paths_by_id):,}", file=sys.stderr)

    path_map: dict[str, str] = {}
    accepted = 0
    skipped_too_few = 0
    skipped_low_dominance = 0
    skipped_form_diff = 0

    for pid, paths in paths_by_id.items():
        n_skus = sum(paths.values())
        if n_skus < MIN_SKUS:
            skipped_too_few += 1
            continue

        # If multiple top-level groups appear, raise the threshold. Genuine
        # form differences (Onions appearing in both Produce and Frozen) get
        # left alone unless one side is overwhelmingly dominant.
        tops = {p.split(">", 1)[0].strip() for p in paths}
        threshold = DOMINANCE_CROSS_TOPLEVEL if len(tops) > 1 else DOMINANCE_THRESHOLD

        dominant_path, n_dom = paths.most_common(1)[0]
        if n_dom / n_skus < threshold:
            if len(tops) > 1:
                skipped_form_diff += 1
            else:
                skipped_low_dominance += 1
            continue

        path_map[pid] = dominant_path
        accepted += 1

    print(f"  accepted:                 {accepted:,}", file=sys.stderr)
    print(f"  skipped (too few SKUs):   {skipped_too_few:,}", file=sys.stderr)
    print(f"  skipped (low dominance):  {skipped_low_dominance:,}", file=sys.stderr)
    print(f"  skipped (form-diff):      {skipped_form_diff:,}", file=sys.stderr)

    lines = [
        '"""product_identity_fixed -> dominant FDC canonical_path map.',
        "",
        "Auto-generated by build_product_identity_canonical_map.py.",
        f"Trust threshold: dominant path covers ≥{int(DOMINANCE_THRESHOLD*100)}% of SKUs",
        f"with this identity (or ≥{int(DOMINANCE_CROSS_TOPLEVEL*100)}% if paths span multiple top-level groups).",
        "",
        "When a row's product_identity_fixed appears in this map, force its",
        "canonical_path to the value here — overrides whatever the LLM emitted",
        "or what fuzzy matching would have picked.",
        '"""',
        "",
        "PRODUCT_IDENTITY_CANONICAL_PATH_MAP: dict[str, str] = {",
    ]
    for pid in sorted(path_map):
        path = path_map[pid].replace('"', "'")
        safe_pid = pid.replace('"', "'")
        lines.append(f'    "{safe_pid}": "{path}",')
    lines.append("}")
    lines.append("")
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT} ({accepted:,} entries)", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
