"""
Curated head dictionary for product classification.
Each entry: (head, path, patterns, exclude, axes)
ORDER MATTERS — more specific entries must come before generic ones.
Patterns match against the lowercased product description.
"""

# ==============================================================
# PRIORITY 1: very specific products that mask generic ones
# ==============================================================
P1 = [
    # --- BAKING SODA (must beat "soda" beverage) ---
    ("Baking Soda", "Pantry > Baking",
     [r"\bbaking soda\b", r"\bsodium bicarbonate\b"],
     [], ["brand","size"]),

    ("Baking Powder", "Pantry > Baking",
     [r"\bbaking powder\b"],
     [], ["brand","size"]),

    # --- DIET / ZERO SODA (must beat plain Soda) ---
    ("Diet Soda", "Beverage > Soda",
     [r"\bdiet (coke|coca[- ]?cola|pepsi|sprite|7[- ]?up|dr pepper|mountain dew|root beer|cola|soda|cream soda)\b",
      r"\bdiet (cherry|vanilla|orange) (coke|cola|pepsi|soda)\b"],
     [r"\bbaking\b", r"\bclub\b", r"\bice cream\b"],
     ["flavor","brand","size","caffeine"]),

    ("Zero-Sugar Soda", "Beverage > Soda",
     [r"\bzero (sugar|cal|calorie)\b.*\b(soda|cola|coke|pepsi|sprite|root beer|drink)\b",
      r"\b(coke|coca[- ]?cola|pepsi|sprite) zero\b",
      r"\b(sugar[- ]?free)\b.*\b(soda|cola|cream soda|root beer)\b"],
     [r"\bbaking\b", r"\bcandy\b"],
     ["flavor","brand","size","caffeine"]),

    # --- PLANT MILKS (must beat dairy Milk) ---
    ("Almond Milk", "Beverage > Plant Milk",
     [r"\balmond[- \s]?milk\b", r"\balmondmilk\b", r"\balmond beverage\b", r"\balmond drink\b"],
     [r"\bcoffee creamer\b"], ["flavor","brand","size","sweetener","organic"]),
    ("Oat Milk", "Beverage > Plant Milk",
     [r"\boat\s*milk\b", r"\boatmilk\b", r"\boat beverage\b", r"\boat drink\b"],
     [], ["flavor","brand","size","sweetener","organic"]),
    ("Soy Milk", "Beverage > Plant Milk",
     [r"\bsoy\s*milk\b", r"\bsoymilk\b", r"\bsoy beverage\b", r"\bsoy drink\b"],
     [], ["flavor","brand","size","sweetener","organic"]),
    ("Coconut Milk Beverage", "Beverage > Plant Milk",
     [r"\bcoconut\s*milk beverage\b", r"\bcoconut\s*milk drink\b",
      r"\bcoconutmilk\b.*\b(beverage|drink|carton)\b"],
     [r"\bcanned\b", r"\b13\.5\s*oz\b", r"\bthai\b", r"\bcurry\b"], ["flavor","brand","size","sweetener","organic"]),
    ("Cashew Milk", "Beverage > Plant Milk",
     [r"\bcashew\s*milk\b", r"\bcashewmilk\b", r"\bcashew beverage\b"],
     [], ["flavor","brand","size","sweetener","organic"]),
    ("Hemp Milk", "Beverage > Plant Milk",
     [r"\bhemp\s*milk\b", r"\bhempmilk\b", r"\bhemp beverage\b"],
     [], ["flavor","brand","size","sweetener","organic"]),
    ("Rice Milk", "Beverage > Plant Milk",
     [r"\brice\s*milk\b", r"\bricemilk\b", r"\brice beverage\b", r"\brice drink\b"],
     [], ["flavor","brand","size","sweetener","organic"]),
    ("Macadamia Milk", "Beverage > Plant Milk",
     [r"\bmacadamia\s*milk\b", r"\bmacadamiamilk\b"],
     [], ["flavor","brand","size","sweetener","organic"]),
    ("Pea Milk", "Beverage > Plant Milk",
     [r"\bpea\s*milk\b", r"\bpeamilk\b", r"\bpea protein milk\b"],
     [], ["flavor","brand","size","sweetener","organic"]),
    ("Pistachio Milk", "Beverage > Plant Milk",
     [r"\bpistachio\s*milk\b", r"\bpistachiomilk\b"],
     [], ["flavor","brand","size","sweetener","organic"]),
    ("Hazelnut Milk", "Beverage > Plant Milk",
     [r"\bhazelnut\s*milk\b"],
     [], ["flavor","brand","size","sweetener","organic"]),
    ("Walnut Milk", "Beverage > Plant Milk",
     [r"\bwalnut\s*milk\b"],
     [], ["flavor","brand","size","sweetener","organic"]),
    ("Flax Milk", "Beverage > Plant Milk",
     [r"\bflax\s*milk\b", r"\bflaxmilk\b"],
     [], ["flavor","brand","size","sweetener","organic"]),

    # --- FLAVORED DAIRY MILK (must beat plain Milk) ---
    ("Chocolate Milk", "Dairy > Flavored Milk",
     [r"\bchocolate milk\b"],
     [r"\b(almond|oat|soy|coconut|cashew|hemp|rice|plant)\b"],
     ["brand","size","fat","organic"]),
    ("Strawberry Milk", "Dairy > Flavored Milk",
     [r"\bstrawberry milk\b"],
     [r"\b(almond|oat|soy|coconut|cashew|hemp|rice|plant)\b"],
     ["brand","size","fat","organic"]),
    ("Vanilla Milk", "Dairy > Flavored Milk",
     [r"\bvanilla milk\b"],
     [r"\b(almond|oat|soy|coconut|cashew|hemp|rice|plant)\b"],
     ["brand","size","fat","organic"]),
    ("Banana Milk", "Dairy > Flavored Milk",
     [r"\bbanana milk\b"],
     [r"\b(almond|oat|soy|coconut|cashew|hemp|rice|plant)\b"],
     ["brand","size","fat","organic"]),
    ("Eggnog", "Dairy > Specialty",
     [r"\beggnog\b", r"\begg nog\b", r"\bnog\b"],
     [r"\b(soap|candle|scent)\b"], ["brand","size","seasonal"]),

    # --- SPECIFIC DAIRY MILK (fat levels) ---
    ("Whole Milk", "Dairy > Milk",
     [r"\bwhole milk\b", r"\bvitamin d milk\b", r"\bwhole vitamin d milk\b"],
     [r"\b(almond|oat|soy|coconut|cashew|hemp|rice|plant|chocolate|strawberry|vanilla)\b"],
     ["brand","size","organic","grass-fed"]),
    ("Reduced-Fat Milk", "Dairy > Milk",
     [r"\b2\s*%\s*milk\b", r"\breduced[- ]?fat milk\b", r"\b2\s*percent milk\b"],
     [r"\b(almond|oat|soy|coconut|cashew|hemp|rice|plant|chocolate|strawberry|vanilla)\b"],
     ["brand","size","organic"]),
    ("Low-Fat Milk", "Dairy > Milk",
     [r"\b1\s*%\s*milk\b", r"\blow[- ]?fat milk\b", r"\b1\s*percent milk\b"],
     [r"\b(almond|oat|soy|coconut|cashew|hemp|rice|plant|chocolate|strawberry|vanilla)\b"],
     ["brand","size","organic"]),
    ("Skim Milk", "Dairy > Milk",
     [r"\bskim milk\b", r"\bnonfat milk\b", r"\bnon[- ]?fat milk\b", r"\bfat[- ]?free milk\b", r"\b0\s*%\s*milk\b"],
     [r"\b(almond|oat|soy|coconut|cashew|hemp|rice|plant)\b"],
     ["brand","size","organic"]),
    ("Lactose-Free Milk", "Dairy > Milk",
     [r"\blactose[- ]?free milk\b", r"\blactaid\b"],
     [], ["brand","size","fat","organic"]),
    ("A2 Milk", "Dairy > Milk",
     [r"\ba2 milk\b", r"\ba2 a2\b"],
     [], ["brand","size","fat"]),
    ("Goat Milk", "Dairy > Milk",
     [r"\bgoat milk\b", r"\bgoat[\']s milk\b"],
     [r"\bsoap\b", r"\blotion\b"], ["brand","size"]),
    ("Buttermilk", "Dairy > Milk",
     [r"\bbuttermilk\b"],
     [r"\bdressing\b", r"\bbiscuit\b", r"\bpancake mix\b", r"\bwaffle\b", r"\bbread\b"],
     ["brand","size","cultured"]),
    ("Raw Milk", "Dairy > Milk",
     [r"\braw milk\b", r"\bunpasteurized milk\b"],
     [], ["brand","size","fat"]),

    # --- ICE CREAM SUBTYPES (must beat Ice Cream) ---
    ("Ice Cream Sandwich", "Frozen > Ice Cream",
     [r"\bice cream sandwich\b", r"\bicecream sandwich\b"],
     [], ["flavor","brand","size"]),
    ("Ice Cream Bar", "Frozen > Ice Cream",
     [r"\bice cream bar\b", r"\bicecream bar\b"],
     [r"\bbakery\b"], ["flavor","brand","size"]),
    ("Ice Cream Cone", "Frozen > Ice Cream",
     [r"\bice cream cone\b", r"\bicecream cone\b", r"\bsugar cone\b", r"\bwaffle cone\b"],
     [], ["flavor","brand","size"]),
    ("Ice Cream Cake", "Frozen > Ice Cream",
     [r"\bice cream cake\b"],
     [], ["flavor","brand","size"]),
    ("Ice Cream Mix", "Frozen > Ice Cream",
     [r"\bice cream mix\b", r"\bsoft serve mix\b"],
     [], ["flavor","brand","size"]),
    ("Ice Cream Sundae", "Frozen > Ice Cream",
     [r"\bsundae\b.*\bice cream\b", r"\bice cream sundae\b"],
     [], ["flavor","brand","size"]),

    # --- OIL VARIANTS (must beat plain Oil) ---
    ("Truffle Oil", "Pantry > Oils & Vinegars",
     [r"\btruffle oil\b"],
     [r"\b(chips|cracker|popcorn|salt|seasoning|cheese|sauce|risotto|pasta sauce)\b"],
     ["brand","size","color"]),
    ("Extra Virgin Olive Oil", "Pantry > Oils & Vinegars",
     [r"\bextra virgin olive oil\b", r"\bevoo\b"],
     [], ["brand","size","origin","organic"]),
    ("Olive Oil", "Pantry > Oils & Vinegars",
     [r"\bolive oil\b"],
     [r"\bextra virgin\b", r"\bcooking spray\b"], ["brand","size","origin","organic"]),
    ("Coconut Oil", "Pantry > Oils & Vinegars",
     [r"\bcoconut oil\b"],
     [r"\bcooking spray\b"], ["brand","size","virgin","organic"]),
    ("Avocado Oil", "Pantry > Oils & Vinegars",
     [r"\bavocado oil\b"],
     [r"\bcooking spray\b"], ["brand","size","organic"]),
    ("Sesame Oil", "Pantry > Oils & Vinegars",
     [r"\bsesame oil\b"],
     [], ["brand","size","toasted"]),
    ("Peanut Oil", "Pantry > Oils & Vinegars",
     [r"\bpeanut oil\b"],
     [], ["brand","size"]),
    ("Canola Oil", "Pantry > Oils & Vinegars",
     [r"\bcanola oil\b"],
     [r"\bcooking spray\b"], ["brand","size","organic"]),
    ("Vegetable Oil", "Pantry > Oils & Vinegars",
     [r"\bvegetable oil\b", r"\bveg oil\b"],
     [r"\bcooking spray\b"], ["brand","size"]),
    ("Sunflower Oil", "Pantry > Oils & Vinegars",
     [r"\bsunflower oil\b"],
     [], ["brand","size"]),
    ("Safflower Oil", "Pantry > Oils & Vinegars",
     [r"\bsafflower oil\b"],
     [], ["brand","size"]),
    ("Corn Oil", "Pantry > Oils & Vinegars",
     [r"\bcorn oil\b"],
     [], ["brand","size"]),
    ("Walnut Oil", "Pantry > Oils & Vinegars",
     [r"\bwalnut oil\b"],
     [], ["brand","size"]),
    ("Grapeseed Oil", "Pantry > Oils & Vinegars",
     [r"\bgrapeseed oil\b", r"\bgrape seed oil\b"],
     [], ["brand","size"]),
    ("MCT Oil", "Pantry > Oils & Vinegars",
     [r"\bmct oil\b", r"\bm\.c\.t\. oil\b"],
     [], ["brand","size"]),
    ("Flaxseed Oil", "Pantry > Oils & Vinegars",
     [r"\bflax(seed)? oil\b"],
     [], ["brand","size"]),
    ("Cooking Spray", "Pantry > Oils & Vinegars",
     [r"\bcooking spray\b", r"\bnon[- ]?stick spray\b", r"\boil spray\b"],
     [], ["brand","size","oil-base"]),

    # --- VINEGAR ---
    ("Balsamic Vinegar", "Pantry > Oils & Vinegars",
     [r"\bbalsamic vinegar\b", r"\bbalsamic glaze\b"],
     [], ["brand","size","aged"]),
    ("Apple Cider Vinegar", "Pantry > Oils & Vinegars",
     [r"\bapple cider vinegar\b", r"\bacv\b"],
     [r"\bdrink\b", r"\bgummy\b", r"\bsupplement\b"], ["brand","size","organic"]),
    ("Red Wine Vinegar", "Pantry > Oils & Vinegars",
     [r"\bred wine vinegar\b"], [], ["brand","size"]),
    ("White Wine Vinegar", "Pantry > Oils & Vinegars",
     [r"\bwhite wine vinegar\b"], [], ["brand","size"]),
    ("Rice Vinegar", "Pantry > Oils & Vinegars",
     [r"\brice vinegar\b", r"\brice wine vinegar\b"], [], ["brand","size"]),
    ("Distilled Vinegar", "Pantry > Oils & Vinegars",
     [r"\bdistilled (white )?vinegar\b", r"\bwhite vinegar\b"], [], ["brand","size"]),
]

# ==============================================================
# PRIORITY 2: more specific products
# ==============================================================
P2 = [
    # --- MAYO ---
    ("Vegan Mayonnaise", "Pantry > Condiments",
     [r"\bvegan mayo(nnaise)?\b", r"\begg[- ]?free mayo(nnaise)?\b", r"\bplant[- ]?based mayo(nnaise)?\b"],
     [], ["flavor","brand","size","organic"]),
    ("Light Mayonnaise", "Pantry > Condiments",
     [r"\blight mayo(nnaise)?\b", r"\blow[- ]?fat mayo(nnaise)?\b", r"\breduced[- ]?fat mayo(nnaise)?\b",
      r"\bfat[- ]?free mayo(nnaise)?\b"],
     [], ["flavor","brand","size"]),
    ("Aioli", "Pantry > Condiments",
     [r"\baioli\b"], [], ["flavor","brand","size"]),
    ("Mayonnaise", "Pantry > Condiments",
     [r"\bmayo(nnaise)?\b"],
     [r"\bsauce\b.*\bsalad\b", r"\bsalad dressing\b", r"\bdressing\b", r"\bsandwich\b"],
     ["flavor","brand","size","organic"]),

    # --- COFFEE VARIANTS ---
    ("Decaf Coffee", "Beverage > Coffee & Tea",
     [r"\bdecaf(feinated)?\b.*\bcoffee\b", r"\bdecaf coffee\b", r"\bcoffee.*\bdecaf\b"],
     [], ["roast","brand","size","form"]),
    ("Cold Brew Coffee", "Beverage > Coffee & Tea",
     [r"\bcold brew\b"], [], ["brand","size","sweetener"]),
    ("Iced Coffee", "Beverage > Coffee & Tea",
     [r"\biced coffee\b", r"\biced latte\b", r"\biced mocha\b"], [], ["brand","size","sweetener"]),
    ("Coffee Pods", "Beverage > Coffee & Tea",
     [r"\b(k[- ]?cup|k cups|coffee pod|nespresso|capsule)s?\b"],
     [r"\bcleaning\b"], ["roast","brand","size","caffeine"]),
    ("Instant Coffee", "Beverage > Coffee & Tea",
     [r"\binstant coffee\b", r"\bcoffee crystal\b"], [], ["brand","size","caffeine"]),
    ("Ground Coffee", "Beverage > Coffee & Tea",
     [r"\bground coffee\b"], [], ["roast","brand","size","caffeine"]),
    ("Coffee Beans", "Beverage > Coffee & Tea",
     [r"\bwhole bean coffee\b", r"\bcoffee beans\b"], [], ["roast","brand","size","origin"]),
    ("Latte", "Beverage > Coffee & Tea",
     [r"\blatte\b"],
     [r"\b(yarn|paint|color)\b"], ["flavor","brand","size","milk"]),
    ("Cappuccino", "Beverage > Coffee & Tea",
     [r"\bcappuccino\b"], [], ["flavor","brand","size"]),
    ("Espresso", "Beverage > Coffee & Tea",
     [r"\bespresso\b"], [], ["flavor","brand","size"]),
    ("Coffee Creamer", "Dairy > Creamers",
     [r"\b(coffee )?creamer\b", r"\bhalf and half\b.*\bcoffee\b"],
     [], ["flavor","brand","size","fat","plant"]),
    ("Coffee", "Beverage > Coffee & Tea",
     [r"\bcoffee\b"],
     [r"\b(cake|cookie|ice cream|candy|chocolate|filter|grinder|mug|maker|table|chair)\b"],
     ["roast","brand","size","caffeine"]),

    # --- TEA VARIANTS ---
    ("Iced Tea", "Beverage > Coffee & Tea",
     [r"\biced tea\b"], [], ["flavor","brand","size","sweetener"]),
    ("Green Tea", "Beverage > Coffee & Tea",
     [r"\bgreen tea\b"], [], ["brand","size","caffeine"]),
    ("Black Tea", "Beverage > Coffee & Tea",
     [r"\bblack tea\b"], [], ["brand","size","caffeine"]),
    ("Herbal Tea", "Beverage > Coffee & Tea",
     [r"\bherbal tea\b", r"\b(chamomile|peppermint|rooibos|ginger) tea\b"],
     [], ["brand","size","blend"]),
    ("Matcha", "Beverage > Coffee & Tea",
     [r"\bmatcha\b"], [], ["brand","size","grade"]),
    ("Chai", "Beverage > Coffee & Tea",
     [r"\bchai\b"], [], ["brand","size","blend"]),
    ("Oolong Tea", "Beverage > Coffee & Tea",
     [r"\boolong\b"], [], ["brand","size"]),
    ("White Tea", "Beverage > Coffee & Tea",
     [r"\bwhite tea\b"], [], ["brand","size"]),
    ("Tea", "Beverage > Coffee & Tea",
     [r"\btea bags?\b", r"\btea\b"],
     [r"\b(towel|kettle|pot|cup|cake|cookie|ice cream)\b"], ["flavor","brand","size","caffeine"]),
    ("Kombucha", "Beverage > Functional",
     [r"\bkombucha\b"], [], ["flavor","brand","size","alcohol"]),

    # --- WATER / SELTZER ---
    ("Sparkling Water", "Beverage > Water",
     [r"\bsparkling water\b", r"\bcarbonated water\b"], [], ["flavor","brand","size"]),
    ("Seltzer", "Beverage > Water",
     [r"\bseltzer\b", r"\bfizzy water\b"], [r"\bhard\b", r"\balcoholic\b", r"\b%\s*alc\b"],
     ["flavor","brand","size"]),
    ("Mineral Water", "Beverage > Water",
     [r"\bmineral water\b"], [], ["brand","size","origin"]),
    ("Coconut Water", "Beverage > Water",
     [r"\bcoconut water\b"], [r"\bcocktail\b"], ["flavor","brand","size","organic"]),
    ("Flavored Water", "Beverage > Water",
     [r"\bflavored water\b", r"\bwater enhancer\b"], [], ["flavor","brand","size"]),
    ("Water", "Beverage > Water",
     [r"\b(spring|purified|distilled|alkaline|filtered|drinking) water\b", r"\bbottled water\b"],
     [r"\bdog\b", r"\bbaby formula\b"], ["brand","size"]),

    # --- SPORT / ENERGY / SHAKES ---
    ("Energy Drink", "Beverage > Functional",
     [r"\benergy drink\b", r"\bred bull\b", r"\bmonster energy\b", r"\brockstar\b", r"\bbang energy\b",
      r"\bcelsius\b", r"\bnos energy\b"],
     [r"\bbar\b.*\bsnack\b"], ["flavor","brand","size","caffeine","sugar"]),
    ("Sports Drink", "Beverage > Functional",
     [r"\bsports drink\b", r"\bgatorade\b", r"\bpowerade\b", r"\belectrolyte drink\b",
      r"\bbody armor\b", r"\bliquid iv\b"],
     [], ["flavor","brand","size","sugar"]),
    ("Protein Shake", "Beverage > Functional",
     [r"\bprotein shake\b", r"\bprotein drink\b", r"\bensure\b.*\bprotein\b", r"\bpremier protein\b"],
     [], ["flavor","brand","size","protein-source"]),
    ("Meal Replacement Shake", "Beverage > Functional",
     [r"\bmeal replacement\b", r"\bensure\b", r"\bboost\b.*\bdrink\b", r"\bsoylent\b"],
     [], ["flavor","brand","size"]),
    ("Smoothie", "Beverage > Functional",
     [r"\bsmoothie\b"], [r"\bbowl\b", r"\bmaker\b"],
     ["flavor","brand","size"]),

    # --- JUICE ---
    ("Orange Juice", "Beverage > Juice",
     [r"\borange juice\b", r"\bnot from concentrate orange\b"], [], ["pulp","brand","size","organic"]),
    ("Apple Juice", "Beverage > Juice",
     [r"\bapple juice\b"], [r"\bcider\b"], ["brand","size","organic"]),
    ("Apple Cider", "Beverage > Juice",
     [r"\bapple cider\b"], [r"\bvinegar\b", r"\bhard\b"], ["brand","size","organic"]),
    ("Grape Juice", "Beverage > Juice",
     [r"\bgrape juice\b"], [], ["brand","size","organic"]),
    ("Cranberry Juice", "Beverage > Juice",
     [r"\bcranberry juice\b"], [], ["brand","size","cocktail"]),
    ("Pineapple Juice", "Beverage > Juice",
     [r"\bpineapple juice\b"], [], ["brand","size"]),
    ("Pomegranate Juice", "Beverage > Juice",
     [r"\bpomegranate juice\b"], [], ["brand","size"]),
    ("Tomato Juice", "Beverage > Juice",
     [r"\btomato juice\b"], [], ["brand","size"]),
    ("Vegetable Juice", "Beverage > Juice",
     [r"\bvegetable juice\b", r"\bv8\b"], [], ["brand","size"]),
    ("Grapefruit Juice", "Beverage > Juice",
     [r"\bgrapefruit juice\b"], [], ["brand","size"]),
    ("Lemonade", "Beverage > Juice",
     [r"\blemonade\b"], [r"\bvodka\b", r"\bhard\b"], ["flavor","brand","size","sweetener"]),
    ("Limeade", "Beverage > Juice",
     [r"\blimeade\b"], [], ["flavor","brand","size"]),
    ("Fruit Juice", "Beverage > Juice",
     [r"\bjuice\b"],
     [r"\b(meat juice|gravy|cooking juice)\b"],
     ["flavor","brand","size","blend"]),

    # --- SODA (after Diet/Zero/Baking) ---
    ("Soda", "Beverage > Soda",
     [r"\b(coca[- ]?cola|coke|pepsi cola|pepsi|sprite|7[- ]?up|dr pepper|mountain dew|root beer|fanta|cream soda|ginger ale|club soda)\b",
      r"\bsoda\b", r"\bcola\b", r"\bsoft drink\b", r"\bpop\b.*\b(can|bottle|fl oz)\b"],
     [r"\bbaking\b", r"\bice cream\b"], ["flavor","brand","size","caffeine"]),

    # --- HOT CHOCOLATE ---
    ("Hot Chocolate", "Beverage > Coffee & Tea",
     [r"\bhot chocolate\b", r"\bhot cocoa\b", r"\bcocoa mix\b"], [], ["flavor","brand","size"]),

    # --- CHEESE TYPES ---
    ("Cheddar Cheese", "Dairy > Cheese", [r"\bcheddar\b"], [r"\bsoup\b", r"\bcracker\b", r"\bsauce\b", r"\bpopcorn\b", r"\bchip\b", r"\bdip\b"], ["form","brand","size","aged"]),
    ("Mozzarella Cheese", "Dairy > Cheese", [r"\bmozzarella\b"], [r"\bsalad\b", r"\bsticks\b.*\bsnack\b"], ["form","brand","size"]),
    ("Parmesan Cheese", "Dairy > Cheese", [r"\bparmesan\b", r"\bparmigiano\b"], [r"\bcrust\b", r"\bcracker\b", r"\bcrisps?\b"], ["form","brand","size"]),
    ("Feta Cheese", "Dairy > Cheese", [r"\bfeta\b"], [r"\bsalad\b"], ["form","brand","size"]),
    ("Brie Cheese", "Dairy > Cheese", [r"\bbrie\b"], [], ["form","brand","size"]),
    ("Gouda Cheese", "Dairy > Cheese", [r"\bgouda\b"], [], ["form","brand","size","smoked"]),
    ("Swiss Cheese", "Dairy > Cheese", [r"\bswiss cheese\b", r"\bemmental\b", r"\bgruyere\b"], [], ["form","brand","size"]),
    ("Monterey Jack Cheese", "Dairy > Cheese", [r"\bmonterey jack\b"], [], ["form","brand","size"]),
    ("Pepper Jack Cheese", "Dairy > Cheese", [r"\bpepper jack\b"], [], ["form","brand","size"]),
    ("Blue Cheese", "Dairy > Cheese", [r"\bblue cheese\b", r"\bgorgonzola\b", r"\broquefort\b", r"\bstilton\b"], [r"\bdressing\b"], ["form","brand","size"]),
    ("Cottage Cheese", "Dairy > Cheese", [r"\bcottage cheese\b"], [], ["fat","brand","size"]),
    ("Cream Cheese", "Dairy > Cheese", [r"\bcream cheese\b", r"\bneufchatel\b"], [], ["flavor","brand","size","whipped"]),
    ("String Cheese", "Dairy > Cheese", [r"\bstring cheese\b", r"\bcheese stick\b"], [], ["brand","size"]),
    ("Goat Cheese", "Dairy > Cheese", [r"\bgoat cheese\b", r"\bchevre\b"], [r"\bsalad\b"], ["form","brand","size"]),
    ("Provolone Cheese", "Dairy > Cheese", [r"\bprovolone\b"], [], ["form","brand","size"]),
    ("Manchego Cheese", "Dairy > Cheese", [r"\bmanchego\b"], [], ["form","brand","size","aged"]),
    ("Havarti Cheese", "Dairy > Cheese", [r"\bhavarti\b"], [], ["form","brand","size"]),
    ("Muenster Cheese", "Dairy > Cheese", [r"\bmuenster\b"], [], ["form","brand","size"]),
    ("Ricotta Cheese", "Dairy > Cheese", [r"\bricotta\b"], [r"\bsalata\b"], ["fat","brand","size"]),
    ("Mascarpone Cheese", "Dairy > Cheese", [r"\bmascarpone\b"], [], ["brand","size"]),
    ("Burrata Cheese", "Dairy > Cheese", [r"\bburrata\b"], [], ["brand","size"]),
    ("American Cheese", "Dairy > Cheese", [r"\bamerican cheese\b", r"\bamerican single\b"], [], ["form","brand","size"]),
    ("Colby Cheese", "Dairy > Cheese", [r"\bcolby\b"], [], ["form","brand","size"]),
    ("Queso Fresco", "Dairy > Cheese", [r"\bqueso fresco\b", r"\bqueso blanco\b", r"\bcotija\b"], [], ["brand","size"]),
    ("Cheese", "Dairy > Cheese", [r"\bcheese\b"], [
        r"\b(cake|cookie|cracker|chip|popcorn|sauce|dressing|spread|dip|stuffed|crust|stick|bites|filled|topping|burger|pizza|sandwich|wrap|burrito|enchilada|taco|quesadilla|empanada|salad|soup|noodle|mac)\b"
    ], ["form","brand","size","kind"]),

    # --- YOGURT ---
    ("Greek Yogurt", "Dairy > Yogurt", [r"\bgreek yogurt\b", r"\byogurt greek\b"], [], ["flavor","fat","brand","size"]),
    ("Skyr", "Dairy > Yogurt", [r"\bskyr\b"], [], ["flavor","brand","size"]),
    ("Kefir", "Dairy > Yogurt", [r"\bkefir\b"], [], ["flavor","brand","size","cultured"]),
    ("Drinkable Yogurt", "Dairy > Yogurt", [r"\bdrinkable yogurt\b", r"\byogurt drink\b", r"\bgo[- ]?gurt\b"], [], ["flavor","brand","size"]),
    ("Frozen Yogurt", "Frozen > Ice Cream", [r"\bfrozen yogurt\b", r"\bfroyo\b"], [], ["flavor","brand","size"]),
    ("Plant-Based Yogurt", "Dairy > Yogurt", [r"\b(coconut|almond|oat|soy|cashew) yogurt\b", r"\bnon[- ]?dairy yogurt\b", r"\bplant[- ]based yogurt\b"], [], ["flavor","base","brand","size"]),
    ("Yogurt", "Dairy > Yogurt", [r"\byogurt\b", r"\byoghurt\b"], [r"\bcovered\b", r"\bbar\b.*\bsnack\b"], ["flavor","fat","brand","size"]),

    # --- BUTTER ---
    ("Salted Butter", "Dairy > Butter", [r"\bsalted butter\b"], [r"\bunsalted\b"], ["brand","size","grass-fed"]),
    ("Unsalted Butter", "Dairy > Butter", [r"\bunsalted butter\b", r"\bsweet cream butter\b"], [], ["brand","size","grass-fed"]),
    ("Plant Butter", "Dairy > Butter", [r"\bplant[- ]?based butter\b", r"\bvegan butter\b", r"\bdairy[- ]?free butter\b"], [r"\bcup\b", r"\bcookie\b", r"\bcracker\b"], ["base","brand","size"]),
    ("Margarine", "Dairy > Butter", [r"\bmargarine\b"], [], ["brand","size"]),
    ("Ghee", "Dairy > Butter", [r"\bghee\b", r"\bclarified butter\b"], [], ["brand","size","grass-fed"]),
    ("Butter", "Dairy > Butter", [r"\bbutter\b"], [
        r"\b(peanut|almond|cashew|sun|soy|seed|cocoa|nut|chocolate|cookie|popcorn|oil|sauce|spray|cream)\b"
    ], ["brand","size","salt"]),

    # --- CREAMS ---
    ("Heavy Cream", "Dairy > Cream", [r"\bheavy cream\b", r"\bheavy whipping cream\b"], [], ["brand","size"]),
    ("Whipping Cream", "Dairy > Cream", [r"\bwhipping cream\b", r"\bwhipped cream\b", r"\bcool whip\b"], [], ["brand","size","topping"]),
    ("Half and Half", "Dairy > Cream", [r"\bhalf[- ]and[- ]half\b", r"\bhalf & half\b"], [], ["brand","size","fat"]),
    ("Sour Cream", "Dairy > Cream", [r"\bsour cream\b"], [r"\bonion\b.*\bdip\b"], ["fat","brand","size"]),

    # --- ICE CREAM (after subtypes) ---
    ("Light Ice Cream", "Frozen > Ice Cream",
     [r"\blight ice cream\b", r"\blow[- ]?fat ice cream\b", r"\breduced[- ]?fat ice cream\b"],
     [], ["flavor","brand","size"]),
    ("No-Sugar-Added Ice Cream", "Frozen > Ice Cream",
     [r"\bno sugar added ice cream\b", r"\bsugar[- ]?free ice cream\b", r"\bketo ice cream\b"],
     [], ["flavor","brand","size"]),
    ("Non-Dairy Ice Cream", "Frozen > Ice Cream",
     [r"\bnon[- ]?dairy ice cream\b", r"\bdairy[- ]?free ice cream\b",
      r"\b(coconut|almond|oat|cashew|soy) (milk )?(ice cream|frozen dessert)\b",
      r"\bvegan ice cream\b"],
     [], ["flavor","base","brand","size"]),
    ("Gelato", "Frozen > Ice Cream", [r"\bgelato\b"], [], ["flavor","brand","size"]),
    ("Sorbet", "Frozen > Ice Cream", [r"\bsorbet\b", r"\bsorbett\b"], [], ["flavor","brand","size"]),
    ("Sherbet", "Frozen > Ice Cream", [r"\bsherbet\b", r"\bsherbert\b"], [], ["flavor","brand","size"]),
    ("Popsicle", "Frozen > Ice Cream", [r"\bpopsicle\b", r"\bice pop\b", r"\bfreezer pop\b", r"\bfrozen pop\b", r"\bfudge bar\b"], [], ["flavor","brand","size"]),
    ("Ice Cream", "Frozen > Ice Cream",
     [r"\bice cream\b", r"\bicecream\b"],
     [], ["flavor","brand","size"]),

    # --- CAKE ---
    ("Cheesecake", "Bakery > Cake", [r"\bcheesecake\b"], [], ["flavor","brand","size"]),
    ("Cake Mix", "Bakery > Cake", [r"\bcake mix\b"], [], ["flavor","brand","size"]),
    ("Cupcake", "Bakery > Cake", [r"\bcupcakes?\b"], [], ["flavor","brand","size"]),
    ("Pound Cake", "Bakery > Cake", [r"\bpound cake\b"], [], ["flavor","brand","size"]),
    ("Bundt Cake", "Bakery > Cake", [r"\bbundt cake\b"], [], ["flavor","brand","size"]),
    ("Angel Food Cake", "Bakery > Cake", [r"\bangel food cake\b"], [], ["flavor","brand","size"]),
    ("Cake Frosting", "Pantry > Baking", [r"\bfrosting\b", r"\bcake icing\b"], [], ["flavor","brand","size"]),
    ("Cake Filling", "Pantry > Baking", [r"\bcake filling\b", r"\bpie filling\b"], [], ["flavor","brand","size"]),
    ("Cake Pop", "Bakery > Cake", [r"\bcake pops?\b"], [], ["flavor","brand","size"]),
    ("Coffee Cake", "Bakery > Cake", [r"\bcoffee cake\b"], [], ["flavor","brand","size"]),
    ("Cake", "Bakery > Cake", [r"\bcakes?\b"], [
        r"\b(rice cake|fish cake|crab cake|pancake|funnel cake|cup cake|cheese cake|ice cream|coffee cake|short cake|carrot cake mix|cake pop|cake mix|bundt|angel food|pound cake|cookie cake|breakfast cake)\b"
    ], ["flavor","brand","size"]),

    # --- COOKIES ---
    ("Cookie Dough", "Bakery > Cookie", [r"\bcookie dough\b"], [r"\bice cream\b"], ["flavor","brand","size"]),
    ("Cookie Mix", "Bakery > Cookie", [r"\bcookie mix\b"], [], ["flavor","brand","size"]),
    ("Sandwich Cookie", "Bakery > Cookie", [r"\bsandwich cookie\b", r"\boreo\b", r"\bnutter butter\b"], [], ["flavor","brand","size"]),
    ("Cookie", "Bakery > Cookie", [r"\bcookies?\b"], [r"\bcake\b", r"\bbread\b", r"\bdough\b"], ["flavor","brand","size"]),

    # --- BROWNIES ---
    ("Brownie Mix", "Bakery > Brownie", [r"\bbrownie mix\b"], [], ["flavor","brand","size"]),
    ("Brownie", "Bakery > Brownie", [r"\bbrownies?\b"], [r"\bmix\b"], ["flavor","brand","size"]),

    # --- PIES ---
    ("Pie Crust", "Bakery > Pie", [r"\bpie crust\b", r"\bpie shell\b", r"\bpastry shell\b"], [], ["brand","size","style"]),
    ("Pie", "Bakery > Pie", [r"\bpies?\b"], [r"\bpot pie\b", r"\bcrust\b", r"\bshell\b", r"\bfilling\b"], ["flavor","brand","size"]),

    # --- BREAD ---
    ("Sourdough Bread", "Pantry > Bread", [r"\bsourdough\b"], [r"\bcracker\b", r"\bcrouton\b"], ["brand","size"]),
    ("Whole Wheat Bread", "Pantry > Bread", [r"\bwhole wheat bread\b", r"\bwhole grain bread\b"], [], ["brand","size","seeds"]),
    ("White Bread", "Pantry > Bread", [r"\bwhite bread\b"], [], ["brand","size"]),
    ("Tortilla", "Pantry > Bread", [r"\btortillas?\b"], [r"\bchip\b", r"\bsoup\b"], ["type","brand","size"]),
    ("Pita Bread", "Pantry > Bread", [r"\bpita bread\b", r"\bpita\b"], [r"\bchip\b"], ["brand","size"]),
    ("Bagel", "Pantry > Bread", [r"\bbagels?\b"], [r"\bbites\b", r"\bchip\b"], ["flavor","brand","size"]),
    ("English Muffin", "Pantry > Bread", [r"\benglish muffin\b"], [], ["brand","size"]),
    ("Hamburger Bun", "Pantry > Bread", [r"\bhamburger buns?\b", r"\bburger buns?\b", r"\bbrioche buns?\b", r"\bsesame buns?\b"], [], ["brand","size"]),
    ("Hot Dog Bun", "Pantry > Bread", [r"\bhot dog buns?\b", r"\bhotdog buns?\b"], [], ["brand","size"]),
    ("Roll", "Pantry > Bread", [r"\bdinner rolls?\b", r"\bsandwich rolls?\b", r"\bsub rolls?\b"], [], ["type","brand","size"]),
    ("Croissant", "Pantry > Bread", [r"\bcroissants?\b"], [], ["flavor","brand","size"]),
    ("Baguette", "Pantry > Bread", [r"\bbaguettes?\b"], [], ["brand","size"]),
    ("Naan", "Pantry > Bread", [r"\bnaan\b"], [], ["flavor","brand","size"]),
    ("Bread", "Pantry > Bread", [r"\bbreads?\b"], [
        r"\b(crumb|stick|stuffing|pudding|cake|machine|pita|tortilla|cracker|cookie|crouton|french toast|garlic bread)\b"
    ], ["type","brand","size"]),

    # --- MUFFIN/SCONE/DONUT ---
    ("Muffin", "Bakery > Muffin", [r"\bmuffins?\b"], [r"\benglish muffin\b", r"\bmix\b"], ["flavor","brand","size"]),
    ("Muffin Mix", "Bakery > Muffin", [r"\bmuffin mix\b"], [], ["flavor","brand","size"]),
    ("Scone", "Bakery > Muffin", [r"\bscones?\b"], [], ["flavor","brand","size"]),
    ("Donut", "Bakery > Muffin", [r"\bdonut\b", r"\bdoughnut\b"], [r"\bhole\b"], ["flavor","brand","size"]),

    # --- PANCAKE / WAFFLE ---
    ("Pancake Mix", "Pantry > Baking", [r"\bpancake mix\b"], [], ["flavor","brand","size"]),
    ("Pancake", "Bakery > Breakfast", [r"\bpancakes?\b"], [r"\bmix\b", r"\bsyrup\b"], ["flavor","brand","size"]),
    ("Waffle Mix", "Pantry > Baking", [r"\bwaffle mix\b"], [], ["flavor","brand","size"]),
    ("Waffle", "Bakery > Breakfast", [r"\bwaffles?\b"], [r"\bmix\b", r"\biron\b", r"\bsyrup\b", r"\bcone\b"], ["flavor","brand","size"]),

    # --- CONDIMENTS (rest) ---
    ("Ketchup", "Pantry > Condiments", [r"\bketchup\b", r"\bcatsup\b"], [], ["flavor","brand","size","organic"]),
    ("Mustard", "Pantry > Condiments", [r"\bmustard\b"], [r"\bgreens\b", r"\bseeds?\b", r"\boil\b", r"\bsauce\b.*\bcooking\b"], ["type","brand","size"]),
    ("Hot Sauce", "Pantry > Condiments", [r"\bhot sauce\b", r"\btabasco\b", r"\bsriracha\b", r"\bcholula\b", r"\bfrank[\']s\b.*\bred hot\b"], [], ["heat","brand","size"]),
    ("Soy Sauce", "Pantry > Condiments", [r"\bsoy sauce\b", r"\btamari\b", r"\bshoyu\b", r"\bcoconut aminos\b"], [], ["sodium","brand","size"]),
    ("BBQ Sauce", "Pantry > Sauces & Salsas", [r"\bbbq sauce\b", r"\bbarbecue sauce\b", r"\bbar[- ]?b[- ]?q sauce\b"], [], ["flavor","brand","size"]),
    ("Buffalo Sauce", "Pantry > Sauces & Salsas", [r"\bbuffalo sauce\b", r"\bbuffalo wing sauce\b"], [], ["heat","brand","size"]),
    ("Worcestershire", "Pantry > Condiments", [r"\bworcestershire\b"], [], ["brand","size"]),
    ("Teriyaki Sauce", "Pantry > Sauces & Salsas", [r"\bteriyaki\b"], [], ["brand","size"]),
    ("Hoisin Sauce", "Pantry > Sauces & Salsas", [r"\bhoisin\b"], [], ["brand","size"]),
    ("Fish Sauce", "Pantry > Sauces & Salsas", [r"\bfish sauce\b"], [], ["brand","size"]),
    ("Oyster Sauce", "Pantry > Sauces & Salsas", [r"\boyster sauce\b"], [], ["brand","size"]),
    ("Pickle Relish", "Pantry > Condiments", [r"\bpickle relish\b", r"\bsweet relish\b", r"\bdill relish\b"], [], ["brand","size"]),
    ("Tartar Sauce", "Pantry > Condiments", [r"\btartar sauce\b"], [], ["brand","size"]),
    ("Cocktail Sauce", "Pantry > Condiments", [r"\bcocktail sauce\b"], [], ["brand","size"]),
    ("Horseradish", "Pantry > Condiments", [r"\bhorseradish\b"], [r"\bsauce\b"], ["brand","size","prepared"]),
    ("Salad Dressing", "Pantry > Condiments", [r"\bsalad dressing\b", r"\bdressing\b"], [r"\bstuffing\b"], ["flavor","brand","size","fat"]),
    ("Marinade", "Pantry > Condiments", [r"\bmarinade\b"], [], ["flavor","brand","size"]),
    ("Pickles", "Pantry > Condiments", [r"\bpickles?\b"], [r"\brelish\b", r"\bginger\b"], ["type","brand","size"]),

    # --- SAUCES (rest) ---
    ("Marinara Sauce", "Pantry > Sauces & Salsas", [r"\bmarinara\b"], [], ["brand","size","organic"]),
    ("Alfredo Sauce", "Pantry > Sauces & Salsas", [r"\balfredo\b"], [], ["brand","size"]),
    ("Pesto", "Pantry > Sauces & Salsas", [r"\bpesto\b"], [], ["flavor","brand","size"]),
    ("Tomato Sauce", "Pantry > Sauces & Salsas", [r"\btomato sauce\b", r"\bpasta sauce\b"], [r"\bmarinara\b"], ["flavor","brand","size","organic"]),
    ("Pizza Sauce", "Pantry > Sauces & Salsas", [r"\bpizza sauce\b"], [], ["brand","size"]),
    ("Cheese Sauce", "Pantry > Sauces & Salsas", [r"\bcheese sauce\b", r"\bnacho cheese\b", r"\bqueso dip\b"], [], ["flavor","brand","size"]),
    ("Curry Sauce", "Pantry > Sauces & Salsas", [r"\bcurry sauce\b", r"\bcurry paste\b", r"\bcurry simmer\b"], [], ["heat","brand","size"]),
    ("Salsa", "Pantry > Sauces & Salsas", [r"\bsalsa\b"], [r"\bdancing\b"], ["heat","flavor","brand","size"]),
    ("Gravy", "Pantry > Sauces & Salsas", [r"\bgravy\b"], [], ["flavor","brand","size","mix"]),
    ("Sauce", "Pantry > Sauces & Salsas", [r"\bsauce\b"], [], ["flavor","brand","size"]),

    # --- SWEETENERS ---
    ("Honey", "Pantry > Sweeteners", [r"\bhoney\b"], [r"\bdew\b", r"\bcomb\b", r"\bmustard\b", r"\broasted\b", r"\bbbq\b", r"\bcandy\b"], ["origin","brand","size","raw"]),
    ("Maple Syrup", "Pantry > Sweeteners", [r"\bmaple syrup\b", r"\bpure maple\b"], [], ["grade","brand","size"]),
    ("Pancake Syrup", "Pantry > Sweeteners", [r"\bpancake syrup\b", r"\btable syrup\b"], [], ["flavor","brand","size"]),
    ("Brown Sugar", "Pantry > Sweeteners", [r"\bbrown sugar\b"], [], ["brand","size"]),
    ("Powdered Sugar", "Pantry > Sweeteners", [r"\bpowdered sugar\b", r"\bconfectioners[\']? sugar\b"], [], ["brand","size"]),
    ("Sugar", "Pantry > Sweeteners", [r"\bgranulated sugar\b", r"\bcane sugar\b", r"\bwhite sugar\b", r"\bpure sugar\b"], [], ["brand","size","organic"]),
    ("Stevia", "Pantry > Sweeteners", [r"\bstevia\b"], [], ["brand","size","form"]),
    ("Agave", "Pantry > Sweeteners", [r"\bagave\b"], [r"\btequila\b", r"\bsyrup\b.*\bcocktail\b"], ["brand","size"]),
    ("Sucralose", "Pantry > Sweeteners", [r"\bsucralose\b", r"\bsplenda\b"], [], ["brand","size"]),
    ("Aspartame", "Pantry > Sweeteners", [r"\baspartame\b", r"\bequal\b.*\bsweetener\b"], [], ["brand","size"]),
    ("Monk Fruit", "Pantry > Sweeteners", [r"\bmonk fruit\b"], [], ["brand","size"]),
    ("Erythritol", "Pantry > Sweeteners", [r"\berythritol\b", r"\bswerve\b"], [], ["brand","size"]),

    # --- BAKING ---
    ("All-Purpose Flour", "Pantry > Baking", [r"\ball[- ]?purpose flour\b", r"\bap flour\b"], [], ["brand","size","organic"]),
    ("Whole Wheat Flour", "Pantry > Baking", [r"\bwhole wheat flour\b", r"\bwhole grain flour\b"], [], ["brand","size","organic"]),
    ("Almond Flour", "Pantry > Baking", [r"\balmond flour\b", r"\balmond meal\b"], [], ["brand","size"]),
    ("Coconut Flour", "Pantry > Baking", [r"\bcoconut flour\b"], [], ["brand","size"]),
    ("Bread Flour", "Pantry > Baking", [r"\bbread flour\b"], [], ["brand","size"]),
    ("Cake Flour", "Pantry > Baking", [r"\bcake flour\b"], [], ["brand","size"]),
    ("Self-Rising Flour", "Pantry > Baking", [r"\bself[- ]?rising flour\b"], [], ["brand","size"]),
    ("Flour", "Pantry > Baking", [r"\bflour\b"], [r"\btortilla\b"], ["type","brand","size"]),
    ("Yeast", "Pantry > Baking", [r"\byeast\b"], [r"\bnutritional yeast\b", r"\bbeer\b"], ["brand","size","type"]),
    ("Vanilla Extract", "Pantry > Baking", [r"\bvanilla extract\b", r"\bvanilla beans?\b"], [], ["brand","size","pure"]),
    ("Cocoa Powder", "Pantry > Baking", [r"\bcocoa powder\b", r"\bunsweetened cocoa\b"], [], ["brand","size","dutch"]),
    ("Chocolate Chips", "Pantry > Baking", [r"\bchocolate chips\b", r"\bchoc chips\b", r"\bsemi[- ]?sweet chips\b"], [], ["type","brand","size"]),
    ("Sweetened Condensed Milk", "Pantry > Baking", [r"\bsweetened condensed milk\b", r"\bcondensed milk\b"], [], ["brand","size"]),
    ("Evaporated Milk", "Pantry > Baking", [r"\bevaporated milk\b"], [], ["brand","size"]),

    # --- PEANUT/NUT BUTTERS ---
    ("Peanut Butter", "Pantry > Spreads", [r"\bpeanut butter\b"], [r"\bcookie\b", r"\bcup\b.*\bcandy\b", r"\bbar\b.*\bsnack\b", r"\bice cream\b"], ["type","brand","size","crunch"]),
    ("Almond Butter", "Pantry > Spreads", [r"\balmond butter\b"], [r"\bcup\b.*\bcandy\b"], ["brand","size"]),
    ("Cashew Butter", "Pantry > Spreads", [r"\bcashew butter\b"], [], ["brand","size"]),
    ("Sunflower Butter", "Pantry > Spreads", [r"\bsunflower (seed )?butter\b", r"\bsunbutter\b"], [], ["brand","size"]),
    ("Nutella", "Pantry > Spreads", [r"\bnutella\b", r"\bhazelnut spread\b", r"\bchocolate hazelnut spread\b"], [], ["brand","size"]),
    ("Jam", "Pantry > Spreads", [r"\bjam\b", r"\bjelly\b", r"\bpreserves\b", r"\bmarmalade\b", r"\bfruit spread\b"], [], ["flavor","brand","size","sugar"]),

    # --- GRAINS / PASTA ---
    ("Spaghetti", "Pantry > Grain", [r"\bspaghetti\b"], [r"\bsauce\b", r"\bsquash\b"], ["brand","size","whole-grain"]),
    ("Penne", "Pantry > Grain", [r"\bpenne\b"], [], ["brand","size"]),
    ("Macaroni", "Pantry > Grain", [r"\bmacaroni\b", r"\belbow pasta\b"], [r"\band cheese\b", r"\bsalad\b"], ["brand","size"]),
    ("Lasagna Noodles", "Pantry > Grain", [r"\blasagna noodles?\b"], [], ["brand","size"]),
    ("Egg Noodles", "Pantry > Grain", [r"\begg noodles?\b"], [], ["brand","size"]),
    ("Ramen Noodles", "Pantry > Grain", [r"\bramen\b"], [], ["flavor","brand","size"]),
    ("Soba Noodles", "Pantry > Grain", [r"\bsoba\b"], [], ["brand","size"]),
    ("Rice Noodles", "Pantry > Grain", [r"\brice noodles?\b", r"\brice stick\b"], [], ["brand","size"]),
    ("Pasta", "Pantry > Grain", [r"\bpasta\b"], [r"\bsauce\b", r"\bsalad\b"], ["shape","brand","size","whole-grain"]),
    ("White Rice", "Pantry > Grain", [r"\bwhite rice\b", r"\blong grain rice\b", r"\bjasmine rice\b", r"\bbasmati\b"], [], ["brand","size"]),
    ("Brown Rice", "Pantry > Grain", [r"\bbrown rice\b"], [], ["brand","size"]),
    ("Wild Rice", "Pantry > Grain", [r"\bwild rice\b"], [], ["brand","size"]),
    ("Quinoa", "Pantry > Grain", [r"\bquinoa\b"], [], ["brand","size","color"]),
    ("Couscous", "Pantry > Grain", [r"\bcouscous\b"], [], ["brand","size"]),
    ("Oatmeal", "Pantry > Grain", [r"\boatmeal\b", r"\brolled oats?\b", r"\bsteel cut oats?\b", r"\binstant oats?\b", r"\boats?\b"], [r"\bmilk\b"], ["type","brand","size"]),
    ("Cereal", "Pantry > Grain", [r"\bcereal\b", r"\bcornflakes?\b", r"\bcheerios\b", r"\bgranola\b"], [r"\bbar\b"], ["flavor","brand","size"]),
    ("Granola", "Snack > Granola", [r"\bgranola\b"], [r"\bbar\b", r"\bcereal\b"], ["flavor","brand","size"]),
    ("Granola Bar", "Snack > Bars", [r"\bgranola bars?\b"], [], ["flavor","brand","size"]),
    ("Rice", "Pantry > Grain", [r"\brice\b"], [r"\bnoodle\b", r"\bcake\b", r"\bmilk\b", r"\bcracker\b", r"\bvinegar\b", r"\bpaper\b", r"\bcooker\b", r"\bsticks?\b"], ["type","brand","size"]),

    # --- SOUP & STOCK ---
    ("Chicken Broth", "Pantry > Soup", [r"\bchicken broth\b", r"\bchicken stock\b"], [], ["brand","size","sodium","organic"]),
    ("Beef Broth", "Pantry > Soup", [r"\bbeef broth\b", r"\bbeef stock\b"], [], ["brand","size","sodium"]),
    ("Vegetable Broth", "Pantry > Soup", [r"\bvegetable broth\b", r"\bveggie broth\b", r"\bvegetable stock\b"], [], ["brand","size","sodium","organic"]),
    ("Bone Broth", "Pantry > Soup", [r"\bbone broth\b"], [], ["base","brand","size","collagen"]),
    ("Bouillon", "Pantry > Soup", [r"\bbouillon\b"], [], ["base","brand","size"]),

    # --- LEGUMES (canned/dry) ---
    ("Black Beans", "Pantry > Legume", [r"\bblack beans?\b"], [], ["form","brand","size","organic"]),
    ("Pinto Beans", "Pantry > Legume", [r"\bpinto beans?\b"], [], ["form","brand","size"]),
    ("Kidney Beans", "Pantry > Legume", [r"\bkidney beans?\b"], [], ["form","brand","size"]),
    ("Chickpeas", "Pantry > Legume", [r"\bchickpeas?\b", r"\bgarbanzo\b"], [], ["form","brand","size"]),
    ("Lentils", "Pantry > Legume", [r"\blentils?\b"], [], ["color","brand","size"]),
    ("Refried Beans", "Pantry > Legume", [r"\brefried beans?\b"], [], ["base","brand","size"]),
    ("Baked Beans", "Pantry > Legume", [r"\bbaked beans?\b"], [], ["flavor","brand","size"]),
    ("Hummus", "Pantry > Spreads", [r"\bhummus\b"], [], ["flavor","brand","size"]),
    ("Tofu", "Pantry > Legume", [r"\btofu\b"], [], ["firmness","brand","size","flavor"]),
    ("Tempeh", "Pantry > Legume", [r"\btempeh\b"], [], ["brand","size","flavor"]),
    ("Edamame", "Pantry > Legume", [r"\bedamame\b"], [], ["form","brand","size"]),

    # --- SPICES ---
    ("Salt", "Pantry > Spices", [r"\bsalt\b"], [
        r"\b(seasoning|popcorn|chip|pretzel|caramel|chocolate|peanut|nut|cracker|sea salt caramel|salt water taffy|epsom)\b"
    ], ["type","brand","size"]),
    ("Pepper", "Pantry > Spices", [r"\bblack pepper\b", r"\bground pepper\b", r"\bwhite pepper\b"], [], ["form","brand","size"]),
    ("Garlic Powder", "Pantry > Spices", [r"\bgarlic powder\b", r"\bgranulated garlic\b"], [], ["brand","size"]),
    ("Onion Powder", "Pantry > Spices", [r"\bonion powder\b"], [], ["brand","size"]),
    ("Paprika", "Pantry > Spices", [r"\bpaprika\b"], [], ["type","brand","size"]),
    ("Cumin", "Pantry > Spices", [r"\bcumin\b"], [], ["form","brand","size"]),
    ("Cinnamon", "Pantry > Spices", [r"\bcinnamon\b"], [r"\b(roll|toast|swirl|raisin|sugar|bun|donut|cookie|cake|cereal|apple|chip|gum)\b"], ["form","brand","size"]),
    ("Chili Powder", "Pantry > Spices", [r"\bchili powder\b"], [], ["brand","size"]),
    ("Curry Powder", "Pantry > Spices", [r"\bcurry powder\b"], [], ["brand","size","blend"]),
    ("Italian Seasoning", "Pantry > Spices", [r"\bitalian seasoning\b", r"\bherbs de provence\b"], [], ["brand","size"]),
    ("Seasoning Blend", "Pantry > Spices", [r"\bseasoning\b"], [r"\bsalt\b"], ["flavor","brand","size"]),

    # --- MEATS ---
    ("Bacon", "Meat & Seafood > Pork", [r"\bbacon\b", r"\bbacn\b"], [r"\b(bacon bit|bacon chip|bacon popcorn|bacon salt|bacon seasoning|blt|bacon lettuce|bacon sandwich|bacon wrap)\b"], ["cut","brand","size","cure"]),
    ("Ham", "Meat & Seafood > Pork", [r"\bhams?\b"], [r"\bsandwich\b", r"\bdeli\b.*\bsalad\b"], ["cut","brand","size","cure"]),
    ("Pork Chop", "Meat & Seafood > Pork", [r"\bpork chops?\b"], [], ["cut","brand","size"]),
    ("Pork Loin", "Meat & Seafood > Pork", [r"\bpork loin\b", r"\bpork tenderloin\b"], [], ["cut","brand","size"]),
    ("Ground Pork", "Meat & Seafood > Pork", [r"\bground pork\b"], [], ["fat","brand","size"]),
    ("Sausage", "Meat & Seafood > Pork", [r"\bsausage\b"], [r"\bgravy\b"], ["type","brand","size"]),
    ("Hot Dog", "Meat & Seafood > Pork", [r"\bhot dogs?\b", r"\bfrankfurters?\b", r"\bwieners?\b", r"\bfranks\b"], [r"\bbun\b", r"\bcorn dog\b"], ["base","brand","size"]),
    ("Pepperoni", "Meat & Seafood > Pork", [r"\bpepperoni\b"], [], ["brand","size"]),
    ("Salami", "Meat & Seafood > Pork", [r"\bsalami\b"], [], ["brand","size"]),
    ("Prosciutto", "Meat & Seafood > Pork", [r"\bprosciutto\b"], [], ["brand","size","aged"]),

    ("Ground Beef", "Meat & Seafood > Beef", [r"\bground beef\b", r"\bhamburger\b.*\b(meat|patty)\b"], [], ["fat","brand","size","grass-fed"]),
    ("Steak", "Meat & Seafood > Beef", [r"\bsteak\b"], [r"\b(sandwich|sauce|seasoning|fries|jerky|burger)\b"], ["cut","brand","size","grade"]),
    ("Beef Roast", "Meat & Seafood > Beef", [r"\bbeef roast\b", r"\bchuck roast\b", r"\bpot roast\b"], [], ["cut","brand","size"]),
    ("Beef Jerky", "Snack > Jerky", [r"\bbeef jerky\b", r"\bjerky\b"], [], ["flavor","brand","size","protein"]),
    ("Corned Beef", "Meat & Seafood > Beef", [r"\bcorned beef\b"], [], ["brand","size"]),
    ("Beef Brisket", "Meat & Seafood > Beef", [r"\bbrisket\b"], [], ["brand","size"]),
    ("Beef", "Meat & Seafood > Beef", [r"\bbeef\b"], [r"\b(jerky|broth|stock|stew|sausage|pot pie|burrito|bacon|gravy|sauce|seasoning)\b"], ["cut","brand","size"]),

    ("Chicken Breast", "Meat & Seafood > Poultry", [r"\bchicken breast\b"], [], ["form","brand","size","organic"]),
    ("Chicken Thigh", "Meat & Seafood > Poultry", [r"\bchicken thighs?\b"], [], ["form","brand","size"]),
    ("Chicken Wings", "Meat & Seafood > Poultry", [r"\bchicken wings?\b"], [], ["flavor","brand","size","cook"]),
    ("Whole Chicken", "Meat & Seafood > Poultry", [r"\bwhole chicken\b", r"\brotisserie chicken\b"], [], ["brand","size"]),
    ("Ground Chicken", "Meat & Seafood > Poultry", [r"\bground chicken\b"], [], ["fat","brand","size"]),
    ("Chicken Tenders", "Meat & Seafood > Poultry", [r"\bchicken tenders?\b", r"\bchicken strips?\b"], [], ["brand","size","cook"]),
    ("Chicken Nuggets", "Meat & Seafood > Poultry", [r"\bchicken nuggets?\b", r"\bchicken nuggz\b"], [], ["brand","size","cook"]),
    ("Chicken", "Meat & Seafood > Poultry", [r"\bchickens?\b"], [r"\b(broth|stock|soup|noodle|salad|wrap|sandwich|burrito|chili|stir fry|sauce|seasoning|bouillon|gravy|pot pie|tikka masala|curry|fried rice|enchilada|fajita|kabob|kebab)\b"], ["cut","brand","size","organic"]),
    ("Turkey Breast", "Meat & Seafood > Poultry", [r"\bturkey breast\b"], [], ["form","brand","size"]),
    ("Ground Turkey", "Meat & Seafood > Poultry", [r"\bground turkey\b"], [], ["fat","brand","size"]),
    ("Whole Turkey", "Meat & Seafood > Poultry", [r"\bwhole turkey\b"], [], ["brand","size"]),
    ("Turkey", "Meat & Seafood > Poultry", [r"\bturkey\b"], [r"\b(broth|sausage|jerky|bacon|burger|sandwich|chili)\b"], ["cut","brand","size"]),

    # --- SEAFOOD ---
    ("Salmon", "Meat & Seafood > Seafood", [r"\bsalmon\b"], [r"\bcat food\b"], ["form","brand","size","wild"]),
    ("Tuna", "Meat & Seafood > Seafood", [r"\btuna\b"], [r"\bnoodle\b", r"\bcasserole\b", r"\bsalad\b.*\bdressing\b"], ["form","brand","size"]),
    ("Shrimp", "Meat & Seafood > Seafood", [r"\bshrimps?\b"], [r"\b(scampi|cocktail dip|pasta dish|pad thai|fried rice)\b"], ["size","brand","cook"]),
    ("Cod", "Meat & Seafood > Seafood", [r"\bcod\b"], [r"\bliver oil\b"], ["form","brand","size"]),
    ("Tilapia", "Meat & Seafood > Seafood", [r"\btilapia\b"], [], ["form","brand","size"]),
    ("Mahi", "Meat & Seafood > Seafood", [r"\bmahi[- ]?mahi\b"], [], ["form","brand","size"]),
    ("Halibut", "Meat & Seafood > Seafood", [r"\bhalibut\b"], [], ["form","brand","size"]),
    ("Sardines", "Meat & Seafood > Seafood", [r"\bsardines?\b"], [], ["packing","brand","size"]),
    ("Anchovies", "Meat & Seafood > Seafood", [r"\banchovies?\b"], [], ["form","brand","size"]),
    ("Crab", "Meat & Seafood > Seafood", [r"\bcrabs?\b"], [r"\bapple\b", r"\bgrass\b"], ["form","brand","size"]),
    ("Lobster", "Meat & Seafood > Seafood", [r"\blobster\b"], [r"\bbisque\b", r"\broll\b"], ["form","brand","size"]),
    ("Scallops", "Meat & Seafood > Seafood", [r"\bscallops?\b"], [], ["form","brand","size"]),

    # --- CANDY ---
    ("Chocolate Bar", "Snack > Chocolate", [r"\bchocolate bars?\b", r"\bcandy bars?\b"], [r"\bgranola\b", r"\bprotein\b", r"\benergy bar\b"], ["type","brand","size"]),
    ("Chocolate Truffle", "Snack > Chocolate", [r"\bchocolate truffles?\b", r"\btruffles?\b"], [r"\boil\b", r"\bsalt\b", r"\bsauce\b", r"\bcheese\b", r"\bhoney\b", r"\bmushroom\b", r"\bpasta\b"], ["filling","brand","size"]),
    ("Chocolate Chips", "Snack > Chocolate", [r"\bchocolate chips?\b", r"\bchocolate chunks?\b"], [r"\bcookie\b", r"\bbaking\b"], ["type","brand","size"]),
    ("Chocolate Covered", "Snack > Chocolate", [r"\bchocolate covered\b"], [], ["base","brand","size"]),
    ("Chocolate Spread", "Pantry > Spreads", [r"\bchocolate spread\b"], [], ["brand","size"]),
    ("Cocoa Mix", "Beverage > Coffee & Tea", [r"\bcocoa mix\b"], [], ["brand","size","sugar"]),
    ("Chocolate", "Snack > Chocolate", [r"\bchocolates?\b"], [
        r"\b(cake|cookie|brownie|ice cream|cereal|granola|chocolate milk|frosting|pudding|chip cookie|sauce|syrup|spread|bread|muffin|protein bar|donut|cocoa mix|mocha latte|truffle oil|baking chips|chocolate chip$|covered|caramel apple|hot chocolate|nutella|drink mix)\b"
    ], ["type","brand","size","cacao"]),
    ("Gummy Candy", "Snack > Candy", [r"\bgumm[iy]e?s?\b", r"\bgumm[iy] bears?\b", r"\bgumm[iy] worms?\b", r"\bsour patch\b", r"\bswedish fish\b", r"\bfruit snacks?\b", r"\bfruit chews?\b"], [r"\bvitamin\b", r"\bsupplement\b"], ["flavor","brand","size"]),
    ("Hard Candy", "Snack > Candy", [r"\bhard candy\b", r"\blollipops?\b", r"\bsuckers?\b", r"\bjolly rancher\b", r"\bwerther[\']s\b"], [], ["flavor","brand","size"]),
    ("Caramel", "Snack > Candy", [r"\bcaramels?\b"], [r"\bapple\b", r"\bsauce\b", r"\bsyrup\b", r"\bice cream\b", r"\bcookie\b", r"\bcoffee\b", r"\bpopcorn\b", r"\blatte\b", r"\bchocolate\b"], ["flavor","brand","size"]),
    ("Toffee", "Snack > Candy", [r"\btoffee\b"], [r"\bbar\b.*\bsnack\b", r"\bcoffee\b"], ["brand","size"]),
    ("Marshmallow", "Snack > Candy", [r"\bmarshmallows?\b"], [r"\bcereal\b", r"\bhot chocolate\b"], ["flavor","brand","size"]),
    ("Licorice", "Snack > Candy", [r"\blicorice\b", r"\btwizzlers?\b", r"\bred vines?\b"], [], ["flavor","brand","size"]),
    ("Mints", "Snack > Candy", [r"\bmints?\b", r"\btic tac\b", r"\baltoid\b", r"\blife saver\b"], [r"\bextract\b", r"\bplant\b", r"\bmint chocolate\b", r"\bmint chip\b"], ["flavor","brand","size"]),
    ("Chewing Gum", "Snack > Candy", [r"\bchewing gum\b", r"\bbubble gum\b", r"\b\bgum\b"], [r"\bcombat\b"], ["flavor","brand","size","sugar"]),

    # --- SNACKS ---
    ("Potato Chips", "Snack > Chips", [r"\bpotato chips?\b", r"\bkettle chips?\b"], [], ["flavor","brand","size"]),
    ("Tortilla Chips", "Snack > Chips", [r"\btortilla chips?\b", r"\bcorn chips?\b", r"\bnacho chips?\b"], [], ["flavor","brand","size"]),
    ("Pita Chips", "Snack > Chips", [r"\bpita chips?\b"], [], ["flavor","brand","size"]),
    ("Veggie Chips", "Snack > Chips", [r"\bveggie chips?\b", r"\bvegetable chips?\b"], [], ["base","flavor","brand","size"]),
    ("Pretzels", "Snack > Pretzels", [r"\bpretzels?\b"], [], ["form","flavor","brand","size"]),
    ("Microwave Popcorn", "Snack > Popcorn", [r"\bmicrowave popcorn\b", r"\bmicrowaveable popcorn\b"], [], ["flavor","brand","size"]),
    ("Kettle Corn", "Snack > Popcorn", [r"\bkettle corn\b"], [], ["brand","size"]),
    ("Popcorn", "Snack > Popcorn", [r"\bpopcorn\b"], [], ["flavor","brand","size"]),
    ("Crackers", "Snack > Crackers", [r"\bcrackers?\b"], [r"\b(graham\b.*\bcrust)\b"], ["flavor","brand","size"]),
    ("Granola Bar", "Snack > Bars", [r"\bgranola bars?\b"], [], ["flavor","brand","size"]),
    ("Protein Bar", "Snack > Bars", [r"\bprotein bars?\b"], [], ["flavor","brand","size"]),
    ("Energy Bar", "Snack > Bars", [r"\benergy bars?\b"], [], ["flavor","brand","size"]),
    ("Cereal Bar", "Snack > Bars", [r"\bcereal bars?\b", r"\bbreakfast bar\b"], [], ["flavor","brand","size"]),
    ("Fig Bar", "Snack > Bars", [r"\bfig bars?\b", r"\bfig newton\b"], [], ["flavor","brand","size"]),
    ("Almonds", "Snack > Nuts & Seeds", [r"\balmonds?\b"], [r"\bbutter\b", r"\bmilk\b", r"\bbeverage\b", r"\bdrink\b", r"\bflour\b", r"\boil\b", r"\bextract\b", r"\bjoy\b"], ["flavor","brand","size","prep"]),
    ("Cashews", "Snack > Nuts & Seeds", [r"\bcashews?\b"], [r"\bbutter\b", r"\bmilk\b", r"\bbeverage\b"], ["flavor","brand","size","prep"]),
    ("Walnuts", "Snack > Nuts & Seeds", [r"\bwalnuts?\b"], [r"\bbutter\b", r"\bmilk\b", r"\boil\b"], ["form","brand","size","prep"]),
    ("Pecans", "Snack > Nuts & Seeds", [r"\bpecans?\b"], [r"\bpie\b", r"\bbutter\b"], ["form","brand","size","prep"]),
    ("Pistachios", "Snack > Nuts & Seeds", [r"\bpistachios?\b"], [r"\bmilk\b", r"\bice cream\b", r"\bgelato\b"], ["flavor","brand","size","shell"]),
    ("Peanuts", "Snack > Nuts & Seeds", [r"\bpeanuts?\b"], [r"\bbutter\b", r"\boil\b", r"\bsauce\b", r"\bm&m\b"], ["flavor","brand","size","shell"]),
    ("Mixed Nuts", "Snack > Nuts & Seeds", [r"\bmixed nuts?\b", r"\bnut mix\b"], [], ["flavor","brand","size"]),
    ("Trail Mix", "Snack > Nuts & Seeds", [r"\btrail mix\b"], [], ["flavor","brand","size"]),
    ("Sunflower Seeds", "Snack > Nuts & Seeds", [r"\bsunflower seeds?\b"], [r"\bbutter\b", r"\boil\b"], ["flavor","brand","size","shell"]),
    ("Pumpkin Seeds", "Snack > Nuts & Seeds", [r"\bpumpkin seeds?\b", r"\bpepitas?\b"], [r"\boil\b"], ["flavor","brand","size"]),
    ("Macadamia Nuts", "Snack > Nuts & Seeds", [r"\bmacadamias?\b", r"\bmacadamia nuts?\b"], [r"\bmilk\b", r"\boil\b"], ["flavor","brand","size"]),

    # --- FROZEN MEALS / FROZEN OTHER ---
    ("Frozen Pizza", "Frozen > Frozen Meals", [r"\bfrozen pizza\b", r"\bpizza\b.*\bfrozen\b"], [r"\bcrust\b", r"\bsauce\b"], ["style","topping","brand","size"]),
    ("Frozen Burrito", "Frozen > Frozen Meals", [r"\bfrozen burrito\b", r"\bburrito\b.*\bfrozen\b"], [], ["filling","brand","size"]),
    ("Frozen Lasagna", "Frozen > Frozen Meals", [r"\bfrozen lasagna\b", r"\blasagna\b.*\bfrozen\b"], [], ["protein","brand","size"]),
    ("Frozen Pot Pie", "Frozen > Frozen Meals", [r"\bpot pie\b", r"\bpotpie\b"], [], ["filling","brand","size"]),
    ("TV Dinner", "Frozen > Frozen Meals", [r"\btv dinner\b", r"\bfrozen meal\b", r"\bfrozen dinner\b", r"\blean cuisine\b", r"\bhealthy choice\b", r"\bstouffer\b.*\bdinner\b", r"\bmarie callender[\']s\b.*\bdinner\b"], [], ["protein","brand","size","cuisine"]),
    ("Frozen Vegetables", "Frozen > Frozen Produce", [r"\bfrozen vegetables?\b", r"\bfrozen veggie\b", r"\bfrozen mixed vegetables\b"], [], ["mix","brand","size","organic"]),
    ("Frozen Fruit", "Frozen > Frozen Produce", [r"\bfrozen fruit\b", r"\bfrozen berries\b", r"\bfrozen mango\b", r"\bfrozen pineapple\b"], [], ["type","brand","size","organic"]),

    # --- COMPOSITE DISHES (these are in Meal supercategory in source) ---
    ("Pizza", "Meal > Composite Dishes", [r"\bpizzas?\b"], [r"\bcrust\b", r"\bsauce\b", r"\brolls?\b.*\bsnack\b"], ["topping","style","brand","size"]),
    ("Pizza Crust", "Pantry > Bread", [r"\bpizza crust\b", r"\bpizza dough\b"], [], ["brand","size","style"]),
    ("Soup", "Meal > Composite Dishes", [r"\bsoups?\b"], [r"\bbroth\b", r"\bstock\b", r"\bbouillon\b", r"\bmix\b.*\bdry\b"], ["type","brand","size"]),
    ("Salad Kit", "Meal > Composite Dishes", [r"\bsalad kit\b", r"\bsalad mix\b"], [], ["type","brand","size"]),
    ("Salad", "Meal > Composite Dishes", [r"\bsalads?\b"], [r"\bdressing\b"], ["type","brand","size"]),
    ("Chili", "Meal > Composite Dishes", [r"\bchili\b"], [r"\bpowder\b", r"\bsauce\b", r"\bpepper\b", r"\boil\b"], ["base","heat","brand","size"]),
    ("Sandwich", "Meal > Composite Dishes", [r"\bsandwich(es)?\b"], [r"\bcookie\b", r"\bice cream\b", r"\bbread\b.*\bonly\b"], ["filling","brand","size"]),
    ("Mac and Cheese", "Meal > Composite Dishes", [r"\bmac (and|n[\']?)? cheese\b", r"\bmacaroni and cheese\b"], [], ["form","brand","size"]),
    ("Burrito", "Meal > Composite Dishes", [r"\bburritos?\b"], [r"\bbowl\b"], ["filling","brand","size"]),
    ("Taco", "Meal > Composite Dishes", [r"\btacos?\b"], [r"\bshell\b", r"\bseasoning\b"], ["filling","brand","size","shell"]),
    ("Lasagna", "Meal > Composite Dishes", [r"\blasagna\b"], [r"\bnoodle\b"], ["protein","brand","size"]),
    ("Curry", "Meal > Composite Dishes", [r"\bcurry\b"], [r"\bpowder\b", r"\bpaste\b", r"\bsauce\b"], ["base","cuisine","brand","size"]),
    ("Stir Fry", "Meal > Composite Dishes", [r"\bstir[- ]?fry\b"], [], ["base","brand","size"]),
    ("Sushi", "Meal > Composite Dishes", [r"\bsushi\b"], [r"\brice\b.*\bdry\b", r"\bnori\b.*\bsheet\b"], ["type","brand","size"]),
    ("Pasta Dish", "Meal > Composite Dishes", [r"\bpasta\b.*\b(dinner|meal|dish|bowl)\b"], [], ["sauce","brand","size"]),
    ("Pot Pie", "Meal > Composite Dishes", [r"\bpot pie\b"], [], ["filling","brand","size"]),
    ("Casserole", "Meal > Composite Dishes", [r"\bcasseroles?\b"], [], ["base","brand","size"]),
    ("Stew", "Meal > Composite Dishes", [r"\bstew\b"], [], ["base","brand","size"]),
    ("Chowder", "Meal > Composite Dishes", [r"\bchowder\b"], [], ["base","brand","size"]),
    ("Quesadilla", "Meal > Composite Dishes", [r"\bquesadillas?\b"], [], ["filling","brand","size"]),
    ("Wrap", "Meal > Composite Dishes", [r"\bwraps?\b"], [r"\bplastic\b", r"\bgift\b"], ["filling","brand","size"]),
    ("Fajita", "Meal > Composite Dishes", [r"\bfajitas?\b"], [], ["protein","brand","size"]),
    ("Enchilada", "Meal > Composite Dishes", [r"\benchiladas?\b"], [], ["filling","brand","size"]),
    ("Empanada", "Meal > Composite Dishes", [r"\bempanadas?\b"], [], ["filling","brand","size"]),
    ("Meatballs", "Meal > Composite Dishes", [r"\bmeatballs?\b"], [], ["base","brand","size"]),
    ("Ramen Bowl", "Meal > Composite Dishes", [r"\bramen\b.*\bbowl\b", r"\bramen\b.*\bcup\b"], [], ["flavor","brand","size"]),
    ("Bowl Meal", "Meal > Composite Dishes", [r"\bbowl\b"], [r"\bsalad\b", r"\bcereal\b", r"\boatmeal\b", r"\bmixing\b"], ["base","brand","size"]),

    # --- PRODUCE (when sold whole) ---
    ("Apples", "Produce > Fruit", [r"\bapples?\b"], [r"\b(juice|sauce|cider|pie|cake|cookie|crisp|chips?|cinnamon|caramel apple|fritter|butter|tart|cobbler|strudel|donut|muffin|bread|chocolate|candy|dump cake|smoothie|drink|vinegar)\b"], ["variety","brand","size","organic"]),
    ("Bananas", "Produce > Fruit", [r"\bbananas?\b"], [r"\bbread\b", r"\bcake\b", r"\bcookie\b", r"\bsmoothie\b", r"\bmilk\b", r"\bchip\b", r"\bsplit\b", r"\bpudding\b", r"\bmuffin\b"], ["brand","size","organic"]),
    ("Oranges", "Produce > Fruit", [r"\boranges?\b"], [r"\bjuice\b", r"\bcake\b", r"\bcookie\b", r"\bcandy\b", r"\bsoda\b", r"\bextract\b", r"\bzest\b", r"\bpeel\b"], ["variety","brand","size"]),
    ("Strawberries", "Produce > Fruit", [r"\bstrawberries\b", r"\bstrawberry\b"], [r"\b(jam|jelly|cake|cookie|pie|smoothie|milk|ice cream|yogurt|preserves|candy|drink|flavor|extract|topping|frosting|sauce|swirl|shortcake|cheesecake)\b"], ["brand","size","organic"]),
    ("Blueberries", "Produce > Fruit", [r"\bblueberries\b"], [r"\b(jam|jelly|muffin|cake|cookie|pancake|smoothie|yogurt|pie|sauce)\b"], ["brand","size","organic","wild"]),
    ("Raspberries", "Produce > Fruit", [r"\braspberries\b"], [r"\b(jam|jelly|sauce|smoothie|yogurt|cake|drink|chocolate)\b"], ["brand","size","organic"]),
    ("Blackberries", "Produce > Fruit", [r"\bblackberries\b"], [r"\b(jam|jelly|sauce)\b"], ["brand","size","organic"]),
    ("Grapes", "Produce > Fruit", [r"\bgrapes?\b"], [r"\b(juice|jelly|jam|wine|tomato|leaves|seed|nut)\b"], ["variety","brand","size","organic"]),
    ("Lemons", "Produce > Fruit", [r"\blemons?\b"], [r"\b(juice|cake|cookie|extract|pepper|zest|peel|aid|lift|pie|bar|cream|tea|water|drop|candy|sorbet|pound cake|drink|bottled)\b"], ["brand","size","organic"]),
    ("Limes", "Produce > Fruit", [r"\blimes?\b"], [r"\b(juice|drink|aid|extract|zest|peel|chip|pie|water|bottled)\b"], ["brand","size"]),
    ("Avocados", "Produce > Fruit", [r"\bavocados?\b"], [r"\b(oil|toast|guacamole|spread|dressing)\b"], ["brand","size","organic"]),
    ("Watermelon", "Produce > Fruit", [r"\bwatermelons?\b"], [r"\b(candy|drink|gum|flavor|sorbet)\b"], ["brand","size","seedless"]),
    ("Pineapple", "Produce > Fruit", [r"\bpineapples?\b"], [r"\b(juice|chunks?|slices?|canned|frozen|cake|drink|sauce|salsa)\b"], ["brand","size","organic"]),
    ("Dried Apricots", "Produce > Fruit", [r"\bdried apricots?\b"], [], ["brand","size","organic","sulfur"]),
    ("Apricots", "Produce > Fruit", [r"\bapricots?\b"], [r"\b(jam|jelly|preserves|sauce|nectar|candy)\b"], ["brand","size","dried","organic"]),
    ("Peaches", "Produce > Fruit", [r"\bpeaches?\b"], [r"\b(jam|jelly|preserves|cobbler|pie|cake|drink|tea|yogurt|ice cream|canned|nectar)\b"], ["brand","size","organic"]),
    ("Pears", "Produce > Fruit", [r"\bpears?\b"], [r"\b(juice|sauce|cake|wine|brandy|drink|salad|nectar)\b"], ["variety","brand","size","organic"]),
    ("Mangoes", "Produce > Fruit", [r"\bmangos?\b", r"\bmangoes\b"], [r"\b(juice|smoothie|sorbet|drink|salsa|chutney|candy|jelly|tea|yogurt|milkshake|chunks?|canned|dried)\b"], ["brand","size","organic"]),

    # --- VEGETABLES ---
    ("Tomatoes", "Produce > Vegetable", [r"\btomatoes?\b"], [r"\b(sauce|paste|juice|soup|ketchup|salsa|canned|stewed|crushed|diced|cherry tomato|sun[- ]?dried)\b"], ["form","brand","size","organic"]),
    ("Cherry Tomatoes", "Produce > Vegetable", [r"\bcherry tomato(es)?\b", r"\bgrape tomato(es)?\b"], [], ["brand","size","organic"]),
    ("Carrots", "Produce > Vegetable", [r"\bcarrots?\b"], [r"\b(juice|cake|muffin|pancake|chip|fries|baby carrots?)\b"], ["form","brand","size","organic"]),
    ("Onions", "Produce > Vegetable", [r"\bonions?\b"], [r"\b(powder|salt|soup|ring|dip|chip|sauce|seasoning|french fried|chive)\b"], ["type","brand","size"]),
    ("Garlic", "Produce > Vegetable", [r"\bgarlic\b"], [r"\b(powder|salt|sauce|bread|knot|aioli|paste|olive oil|herb|chicken|chip|crouton|pasta|dip)\b"], ["form","brand","size","organic"]),
    ("Lettuce", "Produce > Vegetable", [r"\blettuce\b", r"\bromaine\b", r"\biceberg\b"], [], ["type","brand","size","organic"]),
    ("Spinach", "Produce > Vegetable", [r"\bspinach\b"], [r"\b(dip|ravioli|lasagna|pizza|pasta|quiche|frittata|wrap|extract|powder|smoothie)\b"], ["form","brand","size","organic"]),
    ("Kale", "Produce > Vegetable", [r"\bkale\b"], [r"\b(chip|smoothie|powder)\b"], ["form","brand","size","organic"]),
    ("Broccoli", "Produce > Vegetable", [r"\bbroccoli\b"], [r"\b(soup|cheese|casserole|salad|alfredo|stir fry)\b"], ["form","brand","size","organic"]),
    ("Cauliflower", "Produce > Vegetable", [r"\bcauliflower\b"], [r"\b(rice|pizza|bread|tots?|gnocchi|mash|crust|wing|gratin)\b"], ["form","brand","size","organic"]),
    ("Celery", "Produce > Vegetable", [r"\bcelery\b"], [r"\b(salt|seed|soup|juice)\b"], ["brand","size","organic"]),
    ("Cucumbers", "Produce > Vegetable", [r"\bcucumbers?\b"], [r"\b(pickle|water|juice|salad|dressing)\b"], ["brand","size","organic"]),
    ("Bell Peppers", "Produce > Vegetable", [r"\bbell peppers?\b", r"\bsweet peppers?\b"], [], ["color","brand","size","organic"]),
    ("Mushrooms", "Produce > Vegetable", [r"\bmushrooms?\b"], [r"\b(soup|sauce|gravy|burger|risotto|stuffed|pizza|coffee|extract)\b"], ["type","brand","size","organic"]),
    ("Zucchini", "Produce > Vegetable", [r"\bzucchini\b", r"\bcourgette\b"], [r"\b(bread|noodle|cake|fries|chip|spiralized)\b"], ["form","brand","size","organic"]),
    ("Squash", "Produce > Vegetable", [r"\bsquash\b"], [r"\b(soup|casserole|drink|seed|pasta|spaghetti squash|noodle)\b"], ["type","brand","size","organic"]),
    ("Sweet Potatoes", "Produce > Vegetable", [r"\bsweet potatoes?\b", r"\byams?\b"], [r"\b(fries|chip|tot|hash|pie|casserole|noodle)\b"], ["form","brand","size","organic"]),
    ("Potatoes", "Produce > Vegetable", [r"\bpotatoes?\b"], [r"\b(chip|fries|tot|salad|skin|soup|hash|wedge|dumpling|cake|knish|au gratin|scallop|mashed|tater|gnocchi)\b"], ["variety","form","brand","size","organic"]),
    ("Corn", "Produce > Vegetable", [r"\bcorn\b"], [r"\b(syrup|starch|meal|flour|bread|chip|tortilla|popcorn|nuts?|dog|flake|cereal|oil|salsa|relish|husk|silk|pop|kettle)\b"], ["form","brand","size"]),
    ("Green Beans", "Produce > Vegetable", [r"\bgreen beans?\b", r"\bstring beans?\b"], [], ["form","brand","size"]),
    ("Peas", "Produce > Vegetable", [r"\bpeas\b", r"\bsplit peas\b"], [r"\b(soup|protein|nut|chick)\b"], ["form","brand","size","organic"]),
    ("Asparagus", "Produce > Vegetable", [r"\basparagus\b"], [], ["form","brand","size"]),
    ("Brussels Sprouts", "Produce > Vegetable", [r"\bbrussels sprouts?\b", r"\bbrussel sprouts?\b"], [], ["form","brand","size"]),
    ("Cabbage", "Produce > Vegetable", [r"\bcabbage\b"], [r"\bsalad\b", r"\bsoup\b", r"\bsauerkraut\b", r"\broll\b"], ["type","brand","size"]),
]

# ==============================================================
# PRIORITY 3: round-2 additions from unclassified analysis
# ==============================================================
P3 = [
    # --- CANNED TOMATOES (must beat generic Tomatoes) ---
    ("Diced Tomatoes", "Pantry > Canned Vegetables",
     [r"\bdiced tomatoes\b", r"\bpetite diced tomatoes\b"], [], ["flavor","brand","size","organic"]),
    ("Crushed Tomatoes", "Pantry > Canned Vegetables",
     [r"\bcrushed tomatoes\b"], [], ["brand","size","organic"]),
    ("Stewed Tomatoes", "Pantry > Canned Vegetables",
     [r"\bstewed tomatoes\b"], [], ["flavor","brand","size"]),
    ("Whole Peeled Tomatoes", "Pantry > Canned Vegetables",
     [r"\bwhole (peeled )?tomatoes\b", r"\bpeeled tomatoes\b"], [], ["brand","size","organic"]),
    ("Sun-Dried Tomatoes", "Pantry > Canned Vegetables",
     [r"\bsun[- ]?dried tomatoes\b"], [], ["packing","brand","size"]),
    ("Tomato Paste", "Pantry > Canned Vegetables",
     [r"\btomato paste\b"], [], ["brand","size","organic"]),
    ("Tomato Puree", "Pantry > Canned Vegetables",
     [r"\btomato pur[eé]e\b"], [], ["brand","size"]),

    # --- CANNED COCONUT MILK (cooking, not beverage) ---
    ("Coconut Milk", "Pantry > Canned Goods",
     [r"\bcoconut milk\b", r"\bcoconut cream\b"], [r"\bbeverage\b", r"\bdrink\b", r"\bcarton\b", r"\bice cream\b"], ["fat","brand","size","organic"]),

    # --- APPLESAUCE ---
    ("Applesauce", "Pantry > Canned Fruit",
     [r"\bapple ?sauce\b"], [], ["flavor","brand","size","organic","sweetener"]),
    ("Apple Chips", "Snack > Chips",
     [r"\bapple chips?\b"], [], ["flavor","brand","size","organic"]),

    # --- CANNED FRUIT ---
    ("Fruit Cocktail", "Pantry > Canned Fruit",
     [r"\bfruit cocktail\b", r"\bmixed fruit\b.*\b(syrup|juice|cup)\b", r"\bmixed fruit cup\b"], [], ["packing","brand","size"]),
    ("Mandarin Oranges", "Pantry > Canned Fruit",
     [r"\bmandarin oranges\b", r"\bmandarins\b"], [], ["packing","brand","size"]),
    ("Pineapple Chunks", "Pantry > Canned Fruit",
     [r"\bpineapple chunks?\b", r"\bpineapple slices?\b", r"\bpineapple tidbits?\b", r"\bpineapple rings?\b", r"\bcrushed pineapple\b"], [], ["packing","brand","size"]),
    ("Peach Slices", "Pantry > Canned Fruit",
     [r"\bpeach slices?\b", r"\bsliced peaches\b", r"\bpeach halves\b", r"\bpeaches in syrup\b"], [], ["packing","brand","size"]),
    ("Pear Halves", "Pantry > Canned Fruit",
     [r"\bpear halves\b", r"\bsliced pears\b", r"\bpears in syrup\b"], [], ["packing","brand","size"]),

    # --- DRIED FRUIT ---
    ("Raisins", "Snack > Dried Fruit",
     [r"\braisins?\b"], [r"\bbread\b", r"\bcookie\b", r"\bcake\b", r"\boatmeal\b"], ["brand","size","organic"]),
    ("Dried Cranberries", "Snack > Dried Fruit",
     [r"\bdried cranberries\b", r"\bcraisins?\b"], [], ["brand","size","organic"]),
    ("Dried Apricots", "Snack > Dried Fruit",
     [r"\bdried apricots?\b"], [], ["brand","size","organic","sulfur"]),
    ("Dates", "Snack > Dried Fruit",
     [r"\bdates\b", r"\bmedjool\b"], [r"\bdate sugar\b", r"\bdate syrup\b"], ["variety","brand","size","organic"]),
    ("Prunes", "Snack > Dried Fruit",
     [r"\bprunes\b", r"\bdried plums\b"], [r"\bjuice\b"], ["brand","size","organic"]),
    ("Figs", "Snack > Dried Fruit",
     [r"\bdried figs?\b", r"\bfigs\b"], [r"\bbar\b", r"\bjam\b", r"\bspread\b"], ["brand","size","organic"]),

    # --- POWDERED DRINK MIX ---
    ("Drink Mix", "Beverage > Mix",
     [r"\bdrink mix\b", r"\bcrystal light\b", r"\bkool[- ]?aid\b.*\bmix\b", r"\bpowdered drink\b", r"\bwater enhancer\b", r"\bsingles to go\b"], [], ["flavor","brand","size","sugar"]),
    ("Lemonade Mix", "Beverage > Mix",
     [r"\blemonade mix\b", r"\bpowdered lemonade\b"], [], ["flavor","brand","size"]),
    ("Hot Cocoa Mix", "Beverage > Coffee & Tea",
     [r"\bhot cocoa mix\b", r"\bhot chocolate mix\b"], [], ["flavor","brand","size"]),
    ("Iced Tea Mix", "Beverage > Coffee & Tea",
     [r"\biced tea mix\b", r"\binstant iced tea\b"], [], ["flavor","brand","size","sugar"]),

    # --- SPECIFIC DRINKS ---
    ("Tonic Water", "Beverage > Soda",
     [r"\btonic water\b"], [], ["flavor","brand","size"]),
    ("Club Soda", "Beverage > Water",
     [r"\bclub soda\b"], [], ["brand","size"]),
    ("Ginger Ale", "Beverage > Soda",
     [r"\bginger ale\b"], [], ["brand","size"]),
    ("Ginger Beer", "Beverage > Soda",
     [r"\bginger beer\b"], [r"\balcoholic\b"], ["brand","size","spice"]),
    ("Aloe Vera Drink", "Beverage > Functional",
     [r"\baloe vera drink\b", r"\baloe drink\b", r"\baloe juice\b", r"\baloe vera juice\b", r"\baloe vera\b.*\bbeverage\b"], [r"\bgel\b", r"\blotion\b"], ["flavor","brand","size"]),
    ("Bloody Mary Mix", "Beverage > Mix",
     [r"\bbloody mary\b"], [], ["spice","brand","size"]),
    ("Margarita Mix", "Beverage > Mix",
     [r"\bmargarita mix\b"], [r"\btequila\b"], ["flavor","brand","size"]),
    ("Fruit Punch", "Beverage > Juice",
     [r"\bfruit punch\b"], [], ["flavor","brand","size"]),
    ("Horchata", "Beverage > Plant Milk",
     [r"\bhorchata\b"], [], ["brand","size"]),

    # --- PROTEIN POWDER / SUPPLEMENTS ---
    ("Protein Powder", "Pantry > Supplements",
     [r"\bprotein powder\b", r"\bwhey protein\b", r"\bplant protein powder\b", r"\bprotein isolate\b"], [r"\bbar\b", r"\bdrink\b", r"\bshake\b", r"\bcookie\b"], ["flavor","brand","size","protein-source"]),
    ("Vitamins", "Pantry > Supplements",
     [r"\bvitamins?\b", r"\bmultivitamin\b"], [r"\bjuice\b", r"\bmilk\b", r"\benriched\b", r"\bfortified\b"], ["form","brand","size"]),
    ("Collagen Powder", "Pantry > Supplements",
     [r"\bcollagen powder\b", r"\bcollagen peptides\b"], [], ["flavor","brand","size"]),

    # --- SPECIFIC CANDY (after gummy fix) ---
    ("Cotton Candy", "Snack > Candy",
     [r"\bcotton candy\b"], [r"\bflavor\b", r"\bgrape\b.*\bsoda\b", r"\blip\b"], ["flavor","brand","size"]),
    ("Candy Cane", "Snack > Candy",
     [r"\bcandy canes?\b"], [], ["flavor","brand","size"]),
    ("Chocolate Covered Pretzels", "Snack > Chocolate",
     [r"\bchocolate covered pretzels?\b", r"\byogurt covered pretzels?\b"], [], ["flavor","brand","size"]),
    ("Chocolate Covered Almonds", "Snack > Chocolate",
     [r"\bchocolate covered almonds?\b", r"\bchocolate almond clusters?\b"], [], ["type","brand","size"]),
    ("Chocolate Covered Raisins", "Snack > Chocolate",
     [r"\bchocolate covered raisins?\b", r"\braisinets\b"], [], ["brand","size"]),
    ("Chocolate Covered Cherries", "Snack > Chocolate",
     [r"\bchocolate covered cherries\b", r"\bchocolate cherries\b"], [], ["brand","size"]),
    ("Chocolate Covered Strawberries", "Snack > Chocolate",
     [r"\bchocolate covered strawberries\b", r"\bchocolate strawberries\b"], [], ["brand","size"]),
    ("Mints", "Snack > Candy",
     [r"\bbreath mints?\b", r"\bpeppermint candies?\b", r"\bpeppermints?\b.*\bcandy\b"], [], ["flavor","brand","size"]),
    ("Caramels", "Snack > Candy",
     [r"\bcaramels\b", r"\bsoft caramels\b", r"\bsalted caramels\b"], [r"\bsauce\b", r"\bsyrup\b", r"\bcoffee\b"], ["flavor","brand","size"]),

    # --- PREPARED PRODUCE ---
    ("Mashed Potatoes", "Meal > Composite Dishes",
     [r"\bmashed potatoes?\b", r"\binstant potatoes?\b", r"\bpotato flakes\b"], [], ["flavor","brand","size"]),
    ("Hash Browns", "Frozen > Frozen Produce",
     [r"\bhash browns?\b", r"\bshredded potatoes\b"], [], ["form","brand","size"]),
    ("French Fries", "Frozen > Frozen Produce",
     [r"\bfrench fries\b", r"\bfries\b.*\bfrozen\b", r"\btater tots?\b", r"\bsteak fries\b", r"\bcrinkle fries\b"], [r"\bsweet potato\b"], ["form","brand","size"]),
    ("Sweet Potato Fries", "Frozen > Frozen Produce",
     [r"\bsweet potato fries\b", r"\bsweet potato tots\b"], [], ["brand","size"]),
    ("Cauliflower Rice", "Frozen > Frozen Produce",
     [r"\bcauliflower rice\b", r"\briced cauliflower\b"], [], ["brand","size","organic"]),

    # --- OLIVES ---
    ("Olives", "Pantry > Canned Vegetables",
     [r"\bolives\b", r"\bripe olives\b", r"\bpitted olives\b", r"\bkalamata\b", r"\bgreen olives\b", r"\bblack olives\b"], [r"\boil\b", r"\bbread\b", r"\btapenade\b"], ["type","brand","size","stuffed"]),
    ("Olive Tapenade", "Pantry > Spreads",
     [r"\btapenade\b", r"\bolive spread\b"], [], ["brand","size"]),
    ("Capers", "Pantry > Canned Vegetables",
     [r"\bcapers\b"], [], ["brand","size"]),
    ("Artichoke Hearts", "Pantry > Canned Vegetables",
     [r"\bartichoke hearts\b", r"\bartichokes?\b"], [r"\bdip\b", r"\bspinach\b.*\bdip\b"], ["packing","brand","size"]),
    ("Pickled Vegetables", "Pantry > Canned Vegetables",
     [r"\bpickled (jalape|onion|beet|carrot|cabbage|radish|turnip|asparagus|okra)\w*\b", r"\bgiardiniera\b", r"\bsauerkraut\b", r"\bkimchi\b"], [], ["type","brand","size"]),

    # --- WHIPPED TOPPING ---
    ("Whipped Topping", "Dairy > Cream",
     [r"\bwhipped topping\b", r"\bcool whip\b", r"\bnon[- ]?dairy whipped\b"], [], ["flavor","brand","size"]),
    ("Whipped Cream", "Dairy > Cream",
     [r"\bwhipped cream\b", r"\breddi[- ]?wip\b"], [], ["flavor","brand","size"]),

    # --- TOASTER PASTRIES, BREAKFAST SWEETS ---
    ("Toaster Pastry", "Bakery > Breakfast",
     [r"\btoaster (pastry|pastries)\b", r"\bpop[- ]?tarts?\b", r"\btoaster strudel\b"], [], ["flavor","brand","size"]),
    ("Cinnamon Roll", "Bakery > Breakfast",
     [r"\bcinnamon rolls?\b"], [], ["brand","size"]),
    ("Sweet Roll", "Bakery > Breakfast",
     [r"\bsweet rolls?\b", r"\bdanish\b"], [], ["flavor","brand","size"]),

    # --- SUNFLOWER MILK & misc plant milks ---
    ("Sunflower Milk", "Beverage > Plant Milk",
     [r"\bsunflower\s*milk\b", r"\bsunflowermilk\b"], [], ["flavor","brand","size","sweetener"]),
    ("Quinoa Milk", "Beverage > Plant Milk",
     [r"\bquinoa milk\b"], [], ["brand","size"]),
    ("Banana Milk", "Beverage > Plant Milk",
     [r"\bbananamilk\b"], [r"\bdairy\b"], ["brand","size"]),

    # --- HOT BEVERAGES ---
    ("Hot Tea", "Beverage > Coffee & Tea",
     [r"\bhot tea\b"], [], ["flavor","brand","size"]),

    # --- BREAKFAST CEREAL families (specific) ---
    ("Granola", "Snack > Granola",
     [r"\bgranola\b"], [r"\bbar\b", r"\bcereal\b"], ["flavor","brand","size"]),
    ("Cereal Bar", "Snack > Bars",
     [r"\bcereal bars?\b"], [], ["flavor","brand","size"]),
    ("Hot Cereal", "Pantry > Grain",
     [r"\bhot cereal\b", r"\bcream of wheat\b", r"\bgrits\b"], [], ["flavor","brand","size"]),

    # --- CONDIMENTS catch-all extras ---
    ("Steak Sauce", "Pantry > Condiments",
     [r"\bsteak sauce\b", r"\ba\.?1\.?\b"], [], ["brand","size"]),
    ("Chimichurri", "Pantry > Sauces & Salsas",
     [r"\bchimichurri\b"], [], ["brand","size"]),
    ("Pesto Sauce", "Pantry > Sauces & Salsas",
     [r"\bpesto sauce\b"], [], ["flavor","brand","size"]),

    # --- SPECIALTY MEATS ---
    ("Lunch Meat", "Meat & Seafood > Deli",
     [r"\blunch meat\b", r"\bdeli meat\b", r"\bsliced (turkey|ham|chicken|roast beef|bologna|salami)\b", r"\bbologna\b"], [], ["type","brand","size"]),
    ("Bratwurst", "Meat & Seafood > Pork",
     [r"\bbratwurst\b", r"\bbrats?\b.*\bsausage\b"], [], ["brand","size"]),
    ("Chorizo", "Meat & Seafood > Pork",
     [r"\bchorizo\b"], [], ["brand","size","type"]),
    ("Jerky", "Snack > Jerky",
     [r"\bjerky\b", r"\bbiltong\b", r"\bmeat sticks?\b"], [], ["base","flavor","brand","size"]),

    # --- SEAFOOD packs ---
    ("Smoked Salmon", "Meat & Seafood > Seafood",
     [r"\bsmoked salmon\b", r"\blox\b"], [], ["brand","size"]),
    ("Imitation Crab", "Meat & Seafood > Seafood",
     [r"\bimitation crab\b", r"\bsurimi\b"], [], ["brand","size"]),
    ("Fish Sticks", "Frozen > Frozen Meals",
     [r"\bfish sticks?\b", r"\bbreaded fish\b"], [], ["brand","size"]),

    # --- CHEESE PRODUCTS missed ---
    ("Shredded Cheese", "Dairy > Cheese",
     [r"\bshredded cheese\b", r"\bshredded mexican\b", r"\bmexican blend cheese\b", r"\bfour cheese blend\b", r"\bitalian blend cheese\b"], [], ["blend","brand","size"]),
    ("Sliced Cheese", "Dairy > Cheese",
     [r"\bsliced cheese\b", r"\bcheese slices\b", r"\bcheese singles\b"], [], ["type","brand","size"]),

    # --- SOY products ---
    ("Edamame", "Pantry > Legume",
     [r"\bedamame\b"], [], ["form","brand","size"]),
    ("Miso Paste", "Pantry > Sauces & Salsas",
     [r"\bmiso\b"], [r"\bsoup\b"], ["color","brand","size"]),

    # --- PUDDING & GELATIN ---
    ("Pudding", "Pantry > Desserts",
     [r"\bpudding\b"], [r"\bblood\b", r"\bbread pudding\b", r"\brice pudding\b", r"\bchia pudding\b"], ["flavor","brand","size","mix"]),
    ("Gelatin", "Pantry > Desserts",
     [r"\bjell[- ]?o\b", r"\bgelatin\b"], [], ["flavor","brand","size","sugar"]),
    ("Custard", "Pantry > Desserts",
     [r"\bcustard\b"], [], ["flavor","brand","size"]),
    ("Mousse", "Pantry > Desserts",
     [r"\bmousse\b"], [], ["flavor","brand","size"]),

    # --- CHIPS catch-all (for anything still chip-shaped) ---
    ("Cheese Puffs", "Snack > Chips",
     [r"\bcheese puffs?\b", r"\bcheetos\b", r"\bcheese curls?\b", r"\bcheese balls?\b.*\bsnack\b"], [], ["flavor","brand","size"]),
    ("Rice Cakes", "Snack > Chips",
     [r"\brice cakes?\b", r"\bcorn cakes?\b"], [], ["flavor","brand","size"]),
    ("Veggie Straws", "Snack > Chips",
     [r"\bveggie straws?\b", r"\bvegetable straws?\b"], [], ["flavor","brand","size"]),

    # --- ICE / WATER FLAVORINGS ---
    ("Sparkling Juice", "Beverage > Juice",
     [r"\bsparkling (cider|grape|juice)\b"], [], ["flavor","brand","size"]),

    # --- ALCOHOL (small set; treat as out-of-grocery) ---
    ("Wine", "Beverage > Alcohol",
     [r"\bwine\b"], [r"\bvinegar\b", r"\bsauce\b", r"\bcooking wine\b", r"\bwine biscuit\b"], ["type","brand","size","abv"]),
    ("Cooking Wine", "Pantry > Cooking",
     [r"\bcooking wine\b", r"\bsherry cooking\b", r"\bmarsala\b"], [], ["brand","size"]),
    ("Beer", "Beverage > Alcohol",
     [r"\bbeer\b"], [r"\broot beer\b", r"\bginger beer\b", r"\bbeer cheese\b", r"\bbeer batter\b", r"\bbrats\b"], ["type","brand","size","abv"]),
    ("Hard Seltzer", "Beverage > Alcohol",
     [r"\bhard seltzer\b", r"\bspiked seltzer\b", r"\bwhite claw\b"], [], ["flavor","brand","size","abv"]),
    ("Cider", "Beverage > Alcohol",
     [r"\bhard cider\b"], [], ["flavor","brand","size","abv"]),

    # --- INFANT / BABY ---
    ("Baby Food", "Pantry > Baby",
     [r"\bbaby food\b", r"\bstage 1\b", r"\bstage 2\b", r"\bstage 3\b"], [], ["stage","flavor","brand","size"]),
    ("Baby Formula", "Pantry > Baby",
     [r"\bbaby formula\b", r"\binfant formula\b", r"\bsimilac\b", r"\benfamil\b"], [], ["stage","brand","size"]),
    ("Toddler Snack", "Pantry > Baby",
     [r"\btoddler\b.*\bsnack\b", r"\bpuffs\b.*\bbaby\b", r"\bteething biscuit\b"], [], ["flavor","brand","size"]),

    # --- MISC ---
    ("Salsa Verde", "Pantry > Sauces & Salsas",
     [r"\bsalsa verde\b", r"\bgreen salsa\b"], [], ["heat","brand","size"]),
    ("Guacamole", "Pantry > Spreads",
     [r"\bguacamole\b", r"\bguac\b"], [], ["flavor","brand","size"]),
    ("Hummus", "Pantry > Spreads",
     [r"\bhummus\b"], [], ["flavor","brand","size"]),
    ("Bean Dip", "Pantry > Spreads",
     [r"\bbean dip\b", r"\brefried bean dip\b"], [], ["flavor","brand","size"]),
    ("Veggie Dip", "Pantry > Spreads",
     [r"\b(spinach|french onion|ranch|veggie|onion) dip\b"], [], ["flavor","brand","size"]),
    ("Salsa Roja", "Pantry > Sauces & Salsas",
     [r"\bsalsa roja\b", r"\bred salsa\b", r"\bpicante sauce\b"], [], ["heat","brand","size"]),

    # --- SOY / TOFU ---
    ("Tofu", "Pantry > Legume",
     [r"\btofu\b", r"\bsoybean curd\b"], [], ["firmness","brand","size","flavor"]),

    # --- Misc canned ---
    ("Canned Corn", "Pantry > Canned Vegetables",
     [r"\bcanned corn\b", r"\bcorn (kernels|niblets|whole kernel|cream style)\b"], [], ["form","brand","size"]),
    ("Canned Mushrooms", "Pantry > Canned Vegetables",
     [r"\bcanned mushrooms?\b", r"\bsliced mushrooms?\b.*\bcan\b"], [], ["brand","size"]),
    ("Canned Beans", "Pantry > Legume",
     [r"\bcanned (black|pinto|kidney|navy|northern|cannellini|garbanzo|chick) beans\b"], [], ["type","brand","size"]),

    # --- NUT/SEED MISC ---
    ("Coconut Flakes", "Pantry > Baking",
     [r"\bcoconut flakes\b", r"\bshredded coconut\b", r"\bsweetened coconut\b"], [], ["sugar","brand","size"]),
    ("Chia Seeds", "Pantry > Baking",
     [r"\bchia seeds?\b"], [r"\bbar\b", r"\bdrink\b", r"\bpudding\b"], ["brand","size","organic"]),
    ("Flax Seeds", "Pantry > Baking",
     [r"\bflax seeds?\b", r"\bground flax\b", r"\bflaxseed meal\b"], [r"\boil\b", r"\bmilk\b"], ["form","brand","size"]),

    # --- SPECIFIC MEAT-FREE ---
    ("Veggie Burger", "Frozen > Frozen Meals",
     [r"\bveggie burgers?\b", r"\bgarden burgers?\b", r"\bbeyond burger\b", r"\bimpossible burger\b", r"\bplant[- ]?based burger\b"], [], ["base","brand","size"]),
    ("Plant-Based Sausage", "Meat & Seafood > Plant-Based",
     [r"\bplant[- ]?based sausage\b", r"\bvegan sausage\b", r"\bbeyond sausage\b"], [], ["brand","size"]),
    ("Plant-Based Chicken", "Meat & Seafood > Plant-Based",
     [r"\bplant[- ]?based chicken\b", r"\bvegan chicken\b", r"\bvegetarian chicken\b"], [], ["form","brand","size"]),
    ("Plant-Based Ground Beef", "Meat & Seafood > Plant-Based",
     [r"\bbeyond beef\b", r"\bimpossible beef\b", r"\bplant[- ]?based ground\b"], [], ["brand","size"]),

    # --- EGGS ---
    ("Eggs", "Dairy > Eggs",
     [r"\beggs?\b"], [r"\b(noodle|salad|nog|substitute|roll|wash|plant|whites only|drop|liquid eggs|hard boiled|deviled)\b"], ["size","brand","organic","cage-free"]),
    ("Liquid Eggs", "Dairy > Eggs",
     [r"\bliquid eggs?\b", r"\begg whites\b", r"\begg substitute\b", r"\begg beaters\b"], [], ["form","brand","size"]),

    # --- ENERGY DRINK followups (catch more brands) ---
    ("Caffeinated Drink", "Beverage > Functional",
     [r"\bcaffeine drink\b", r"\bcaffeinated drink\b", r"\bspark energy\b"], [], ["flavor","brand","size","caffeine"]),

    # --- BAKING MIX (general) ---
    ("Baking Mix", "Pantry > Baking",
     [r"\bbaking mix\b", r"\ball[- ]?purpose baking\b", r"\bbisquick\b", r"\bbatter mix\b", r"\bbiscuit mix\b", r"\bgluten[- ]?free baking mix\b"], [], ["flavor","brand","size","gluten-free"]),
    ("Biscuit Mix", "Pantry > Baking",
     [r"\bbiscuit mix\b"], [], ["flavor","brand","size"]),
    ("Cornbread Mix", "Pantry > Baking",
     [r"\bcornbread mix\b", r"\bcorn bread mix\b"], [], ["flavor","brand","size"]),
    ("Bread Mix", "Pantry > Baking",
     [r"\bbread mix\b"], [r"\bcornbread\b", r"\bbiscuit\b"], ["flavor","brand","size"]),

    # --- BREADCRUMBS / COATINGS ---
    ("Breadcrumbs", "Pantry > Baking",
     [r"\bbread ?crumbs?\b", r"\bpanko\b", r"\bcracker meal\b"], [], ["flavor","brand","size","gluten-free"]),
    ("Fish Breading", "Pantry > Baking",
     [r"\bfish breading\b", r"\bfish fry\b", r"\bfish coating\b"], [], ["flavor","brand","size"]),
    ("Coating Mix", "Pantry > Baking",
     [r"\bcoating mix\b", r"\bshake[- ]?n[- ]?bake\b", r"\bextra crispy mix\b"], [], ["flavor","brand","size"]),
    ("Stuffing", "Pantry > Baking",
     [r"\bstuffing\b", r"\bdressing mix\b.*\bbread\b"], [r"\bsalad dressing\b"], ["flavor","brand","size"]),

    # --- BISCUITS ---
    ("Biscuits", "Bakery > Bread",
     [r"\bbiscuits?\b"], [r"\bmix\b", r"\bcookie\b", r"\bdog\b", r"\bcracker\b", r"\bgravy\b"], ["flavor","brand","size"]),

    # --- CAJUN/SEASONED MEAT (already handled mostly, add cured meats) ---
    ("Sopressata", "Meat & Seafood > Deli",
     [r"\bsopressata\b", r"\bsoppressata\b"], [], ["brand","size"]),
    ("Mortadella", "Meat & Seafood > Deli",
     [r"\bmortadella\b"], [], ["brand","size"]),
    ("Capicola", "Meat & Seafood > Deli",
     [r"\bcapicola\b", r"\bcapocollo\b"], [], ["brand","size"]),

    # --- VEGETABLES missed ---
    ("Shallots", "Produce > Vegetable",
     [r"\bshallots?\b"], [], ["form","brand","size"]),
    ("Leeks", "Produce > Vegetable",
     [r"\bleeks?\b"], [], ["form","brand","size"]),
    ("Ginger Root", "Produce > Vegetable",
     [r"\bginger root\b", r"\bfresh ginger\b"], [r"\bbeer\b", r"\bale\b", r"\bcandy\b", r"\bjuice\b"], ["form","brand","size"]),
    ("Eggplant", "Produce > Vegetable",
     [r"\beggplant\b", r"\baubergine\b"], [r"\bdip\b", r"\bbabaganoush\b", r"\bbaba ganoush\b"], ["brand","size","organic"]),
    ("Beets", "Produce > Vegetable",
     [r"\bbeets?\b"], [r"\bsugar\b", r"\bjuice\b", r"\bpowder\b", r"\bchip\b", r"\bcandy\b", r"\bgreens\b"], ["form","brand","size"]),
    ("Radishes", "Produce > Vegetable",
     [r"\bradishes?\b"], [], ["type","brand","size"]),
    ("Turnips", "Produce > Vegetable",
     [r"\bturnips?\b"], [r"\bgreens?\b"], ["form","brand","size"]),
    ("Parsnips", "Produce > Vegetable",
     [r"\bparsnips?\b"], [], ["form","brand","size"]),
    ("Okra", "Produce > Vegetable",
     [r"\bokra\b"], [], ["form","brand","size"]),

    # --- CARAMEL APPLE KIT ---
    ("Caramel Apple Kit", "Snack > Candy",
     [r"\bcaramel apple\b.*\bkit\b", r"\bcaramel apple dipping\b", r"\bcaramel apple wrap\b"], [], ["brand","size"]),
    ("Caramel Apple", "Snack > Candy",
     [r"\bcaramel apples?\b"], [r"\bflavor\b", r"\bbar\b", r"\bsalad\b"], ["brand","size"]),

    # --- LIQUID AMINOS / SUBSTITUTES ---
    ("Liquid Aminos", "Pantry > Condiments",
     [r"\bliquid aminos\b", r"\bbragg\b.*\baminos\b", r"\bcoconut aminos\b"], [], ["brand","size"]),

    # --- TONIC / CARBONATED ---
    ("Sparkling Lemonade", "Beverage > Juice",
     [r"\bsparkling lemonade\b"], [], ["flavor","brand","size"]),

    # --- COOKIES varieties (most are caught by Cookie) ---
    ("Sugar Cookie", "Bakery > Cookie",
     [r"\bsugar cookies?\b"], [], ["flavor","brand","size"]),
    ("Chocolate Chip Cookie", "Bakery > Cookie",
     [r"\bchocolate chip cookies?\b"], [], ["brand","size"]),
    ("Oatmeal Cookie", "Bakery > Cookie",
     [r"\boatmeal cookies?\b", r"\boatmeal raisin cookies?\b"], [], ["brand","size"]),

    # --- DELI ITEMS ---
    ("Deli Roll", "Pantry > Bread",
     [r"\bdeli rolls?\b"], [], ["brand","size"]),

    # --- ASIAN PRODUCTS ---
    ("Wonton Wrappers", "Pantry > Refrigerated Doughs",
     [r"\bwonton wrappers?\b", r"\bwon ton skins?\b"], [], ["brand","size"]),
    ("Egg Roll Wrappers", "Pantry > Refrigerated Doughs",
     [r"\begg roll wrappers?\b"], [], ["brand","size"]),
    ("Phyllo Dough", "Pantry > Refrigerated Doughs",
     [r"\bphyllo\b", r"\bfilo\b"], [], ["brand","size"]),
    ("Puff Pastry", "Pantry > Refrigerated Doughs",
     [r"\bpuff pastry\b"], [], ["brand","size"]),

    # --- LUNCH KITS / PREPARED ---
    ("Lunch Kit", "Meal > Composite Dishes",
     [r"\blunchables\b", r"\blunch kit\b", r"\bmunchables\b"], [], ["base","brand","size"]),

    # --- CHIPS for fish (lures) — noise to exclude ---
]

# Combine all priorities
HEAD_DICT = P1 + P2 + P3

print(f"head dictionary: {len(HEAD_DICT)} entries")
