"""Pantry family — pasta, sauces, spices, oils, soup, condiments, baking mixes."""
from __future__ import annotations

FAMILY = "Pantry"

# Last-resort family-level fallbacks. Only fire when no specific keyword
# matched in title or path. Prevents generic "soup" from beating specific
# "asparagus" when both could match.
GENERIC_TYPE_LABELS = {
    "Sauce", "Salsa", "Soup", "Oil", "Vinegar", "Pasta", "Noodles",
    "Seasoning", "Rice", "Oats",
    "Mustard", "Ketchup", "Mayonnaise", "Pesto", "Sriracha",
    "Salt", "Pepper",  # generic — let specific salts/peppers win first
    "Stock",  # generic — let specific bases (Beef Base etc.) win first
}

SUB_FAMILY_BY_TYPE: dict[str, str] = {
    # Pasta shapes
    **{t: "Pasta" for t in [
        "Spaghetti", "Penne", "Macaroni", "Linguine", "Fettuccine",
        "Rigatoni", "Rotini", "Bowtie", "Farfalle", "Angel Hair",
        "Lasagna Noodles", "Orzo", "Couscous", "Ramen", "Udon",
        "Shells", "Elbow", "Ziti", "Capellini", "Vermicelli",
        "Egg Noodles", "Rice Noodles", "Soba", "Cavatappi",
    ]},
    # Oil
    **{t: "Oil" for t in [
        "Olive Oil", "Canola Oil", "Vegetable Oil", "Coconut Oil",
        "Avocado Oil", "Sunflower Oil", "Sesame Oil", "Peanut Oil",
        "Grapeseed Oil", "Walnut Oil", "Truffle Oil", "Corn Oil",
    ]},
    # Sauces
    **{t: "Sauces & Salsas" for t in [
        "Pasta Sauce", "Marinara Sauce", "Alfredo Sauce", "Pesto",
        "Barbecue Sauce", "Hot Sauce", "Soy Sauce", "Teriyaki Sauce",
        "Worcestershire Sauce", "Sriracha", "Ketchup", "Mustard",
        "Mayonnaise", "Tartar Sauce", "Cocktail Sauce", "Cheese Sauce",
        "Salsa", "Sauce",
    ]},
    # Spices
    **{t: "Spices & Seasonings" for t in [
        "Salt", "Pepper", "Cinnamon", "Garlic Powder", "Onion Powder",
        "Paprika", "Cumin", "Oregano", "Basil", "Thyme", "Rosemary",
        "Chili Powder", "Curry Powder", "Bay Leaves", "Cayenne",
        "Turmeric", "Ginger", "Nutmeg", "Allspice", "Saffron",
        "Vanilla", "Seasoning",
        # Salt sub-varieties (TYPE level, not tier — they're distinct salts)
        "Himalayan Pink Salt", "Sea Salt", "Kosher Salt", "Smoked Salt",
        "Truffle Salt", "Black Salt", "Pink Salt", "Hawaiian Salt",
        "Celtic Salt", "Fleur de Sel", "Flaky Salt", "Rock Salt",
        "Iodized Salt", "Garlic Salt", "Onion Salt", "Seasoned Salt",
        "Margarita Salt",
        # BBQ rubs — distinct from generic seasoning
        "BBQ Rub", "Steak Rub", "Chicken Rub", "Pork Rub", "Brisket Rub",
        "Dry Rub",
    ]},
    # Bouillon / broth / stocks — moved out of "seasonings" since they're stocks
    **{t: "Bouillon & Broth" for t in [
        "Bouillon", "Bouillon Cubes", "Broth Base", "Soup Base",
        "Demi Glace", "Stock", "Beef Base", "Chicken Base", "Pork Base",
        "Turkey Base", "Ham Base", "Clam Base", "Shrimp Base",
        "Vegetable Base", "Fish Base",
    ]},
    # Vinegars
    **{t: "Vinegar" for t in [
        "Apple Cider Vinegar", "Balsamic Vinegar", "Red Wine Vinegar",
        "White Wine Vinegar", "Rice Vinegar", "Distilled Vinegar",
    ]},
    # Baking Mixes
    **{t: "Baking Mixes" for t in [
        "Cake Mix", "Pancake Mix", "Waffle Mix", "Brownie Mix",
        "Cookie Mix", "Muffin Mix", "Biscuit Mix", "Bread Mix",
        "Doughnut Mix", "Scone Mix", "Dough Mix",
    ]},
    # Grains
    **{t: "Grain" for t in [
        "Rice", "White Rice", "Brown Rice", "Jasmine Rice", "Basmati Rice",
        "Quinoa", "Barley", "Bulgur", "Farro", "Millet", "Spelt", "Teff",
        "Wheat", "Wheat Berries", "Cornmeal", "Polenta",
        "Oats", "Steel Cut Oats", "Rolled Oats", "Instant Oats",
    ]},
    # Canned Vegetables
    **{t: "Canned Vegetables" for t in [
        "Gigantes Beans", "Grilling Beans", "Vegetable Bean Blend",
        "Chili Beans", "Red Beans", "White Beans", "Fava Beans",
        "Asparagus", "Green Beans", "Carrots", "Corn", "Peas",
        "Tomatoes", "Diced Tomatoes", "Crushed Tomatoes", "Tomato Paste",
        "Tomato Sauce", "Stewed Tomatoes", "Whole Tomatoes",
        "Lima Beans", "Chickpeas", "Black Beans", "Pinto Beans",
        "Kidney Beans", "Cannellini Beans", "Navy Beans", "Great Northern Beans",
        "Garbanzo Beans", "Refried Beans", "Baked Beans", "Pork & Beans",
        "Mushrooms", "Beets", "Sauerkraut", "Spinach", "Pumpkin",
        "Mixed Vegetables", "Hominy", "Bamboo Shoots", "Water Chestnuts",
        "Artichoke Hearts", "Hearts of Palm", "Roasted Red Peppers",
        "Olives", "Capers", "Pickles", "Pickled Beets",
    ]},
    # Soup is its own
    **{t: "Soup" for t in [
        "Chicken Soup", "Beef Soup", "Tomato Soup", "Vegetable Soup",
        "Mushroom Soup", "Lentil Soup", "Bean Soup", "Minestrone",
        "Clam Chowder", "Chicken Noodle Soup", "Broccoli Cheddar Soup",
        "French Onion Soup", "Miso Soup",
    ]},
}

TYPE_KEYWORDS: list[tuple[str, str]] = [
    # ---- Pasta shapes (compound first)
    ("angel hair",          "Angel Hair"),
    ("lasagna noodle",      "Lasagna Noodles"),
    ("egg noodle",          "Egg Noodles"),
    ("rice noodle",         "Rice Noodles"),
    ("spaghetti",           "Spaghetti"),
    ("penne",               "Penne"),
    ("rigatoni",            "Rigatoni"),
    ("rotini",              "Rotini"),
    ("bowtie",              "Bowtie"),
    ("farfalle",            "Farfalle"),
    ("linguine",            "Linguine"),
    ("fettuccine",          "Fettuccine"),
    ("macaroni",            "Macaroni"),
    ("orzo",                "Orzo"),
    ("couscous",            "Couscous"),
    ("ramen",               "Ramen"),
    ("udon",                "Udon"),
    ("soba",                "Soba"),
    ("cavatappi",           "Cavatappi"),
    ("capellini",           "Capellini"),
    ("vermicelli",          "Vermicelli"),
    ("ziti",                "Ziti"),
    ("elbow",               "Elbow"),
    ("shells",              "Shells"),
    # ---- Oils
    ("olive oil",           "Olive Oil"),
    ("canola oil",          "Canola Oil"),
    ("vegetable oil",       "Vegetable Oil"),
    ("coconut oil",         "Coconut Oil"),
    ("avocado oil",         "Avocado Oil"),
    ("sunflower oil",       "Sunflower Oil"),
    ("sesame oil",          "Sesame Oil"),
    ("peanut oil",          "Peanut Oil"),
    ("grapeseed oil",       "Grapeseed Oil"),
    ("walnut oil",          "Walnut Oil"),
    ("truffle oil",         "Truffle Oil"),
    ("corn oil",            "Corn Oil"),
    # ---- Sauces (compound first)
    ("pasta sauce",         "Pasta Sauce"),
    ("marinara sauce",      "Marinara Sauce"),
    ("alfredo sauce",       "Alfredo Sauce"),
    ("barbecue sauce",      "Barbecue Sauce"),
    ("bbq sauce",           "Barbecue Sauce"),
    ("hot sauce",           "Hot Sauce"),
    ("soy sauce",           "Soy Sauce"),
    ("teriyaki sauce",      "Teriyaki Sauce"),
    ("worcestershire",      "Worcestershire Sauce"),
    ("tartar sauce",        "Tartar Sauce"),
    ("cocktail sauce",      "Cocktail Sauce"),
    ("cheese sauce",        "Cheese Sauce"),
    ("pesto",               "Pesto"),
    ("sriracha",            "Sriracha"),
    ("ketchup",             "Ketchup"),
    ("mustard",             "Mustard"),
    ("mayonnaise",          "Mayonnaise"),
    ("salsa",               "Salsa"),
    # ---- Vinegars
    ("apple cider vinegar", "Apple Cider Vinegar"),
    ("balsamic vinegar",    "Balsamic Vinegar"),
    ("red wine vinegar",    "Red Wine Vinegar"),
    ("white wine vinegar",  "White Wine Vinegar"),
    ("rice vinegar",        "Rice Vinegar"),
    ("distilled vinegar",   "Distilled Vinegar"),
    # ---- Baking mixes
    ("pancake mix",         "Pancake Mix"),
    ("waffle mix",          "Waffle Mix"),
    ("cake mix",            "Cake Mix"),
    ("brownie mix",         "Brownie Mix"),
    ("cookie mix",          "Cookie Mix"),
    ("muffin mix",          "Muffin Mix"),
    ("biscuit mix",         "Biscuit Mix"),
    ("bread mix",           "Bread Mix"),
    ("doughnut mix",        "Doughnut Mix"),
    ("donut mix",           "Doughnut Mix"),
    ("scone mix",           "Scone Mix"),
    ("dough mix",           "Dough Mix"),
    # ---- Grains
    ("steel cut oat",       "Steel Cut Oats"),
    ("rolled oat",          "Rolled Oats"),
    ("instant oat",         "Instant Oats"),
    ("oatmeal",             "Oats"),
    ("oats",                "Oats"),
    ("brown rice",          "Brown Rice"),
    ("white rice",          "White Rice"),
    ("jasmine rice",        "Jasmine Rice"),
    ("basmati rice",        "Basmati Rice"),
    ("rice",                "Rice"),
    ("quinoa",              "Quinoa"),
    ("barley",              "Barley"),
    ("bulgur",              "Bulgur"),
    ("farro",               "Farro"),
    ("millet",              "Millet"),
    ("spelt",               "Spelt"),
    ("teff",                "Teff"),
    ("wheat berry",         "Wheat Berries"),
    ("cornmeal",            "Cornmeal"),
    ("polenta",             "Polenta"),
    # ---- Canned Vegetables (multi-word first to beat "beans" etc.)
    ("chili bean",          "Chili Beans"),
    ("red kidney bean",     "Kidney Beans"),
    ("red bean",            "Red Beans"),
    ("white bean",          "White Beans"),
    ("fava bean",           "Fava Beans"),
    ("butter baby bean",    "Lima Beans"),
    ("butter large bean",   "Lima Beans"),
    ("butter bean",         "Lima Beans"),
    ("gigantes bean",       "Gigantes Beans"),
    ("giant bean",          "Gigantes Beans"),
    ("grillin' bean",       "Grilling Beans"),
    ("grilling bean",       "Grilling Beans"),
    ("vegetable & bean blend", "Vegetable Bean Blend"),
    ("vegetable and bean blend", "Vegetable Bean Blend"),
    ("vegetable bean blend", "Vegetable Bean Blend"),
    ("garbanzo bean",       "Garbanzo Beans"),
    ("garbanzo",            "Garbanzo Beans"),
    ("chick pea",           "Chickpeas"),
    ("chickpea",            "Chickpeas"),
    ("lima bean",           "Lima Beans"),
    ("black bean",          "Black Beans"),
    ("pinto bean",          "Pinto Beans"),
    ("kidney bean",         "Kidney Beans"),
    ("cannellini bean",     "Cannellini Beans"),
    ("navy bean",           "Navy Beans"),
    ("great northern bean", "Great Northern Beans"),
    ("refried bean",        "Refried Beans"),
    ("baked bean",          "Baked Beans"),
    ("pork & beans",        "Pork & Beans"),
    ("pork and beans",      "Pork & Beans"),
    ("green bean",          "Green Beans"),
    ("snap bean",           "Green Beans"),
    ("crushed tomato",      "Crushed Tomatoes"),
    ("diced tomato",        "Diced Tomatoes"),
    ("stewed tomato",       "Stewed Tomatoes"),
    ("whole tomato",        "Whole Tomatoes"),
    ("tomato paste",        "Tomato Paste"),
    ("tomato sauce",        "Tomato Sauce"),
    ("tomato",              "Tomatoes"),
    ("artichoke heart",     "Artichoke Hearts"),
    ("hearts of palm",      "Hearts of Palm"),
    ("roasted red pepper",  "Roasted Red Peppers"),
    ("water chestnut",      "Water Chestnuts"),
    ("bamboo shoot",        "Bamboo Shoots"),
    ("mixed vegetable",     "Mixed Vegetables"),
    ("pickled beet",        "Pickled Beets"),
    ("hominy",              "Hominy"),
    ("sauerkraut",          "Sauerkraut"),
    ("asparagus",           "Asparagus"),
    ("carrot",              "Carrots"),
    ("corn",                "Corn"),
    ("peas",                "Peas"),
    ("mushroom",            "Mushrooms"),
    ("beet",                "Beets"),
    ("spinach",             "Spinach"),
    ("pumpkin",             "Pumpkin"),
    ("caper",               "Capers"),
    # ---- Soups
    ("chicken noodle soup", "Chicken Noodle Soup"),
    ("broccoli cheddar soup","Broccoli Cheddar Soup"),
    ("french onion",        "French Onion Soup"),
    ("clam chowder",        "Clam Chowder"),
    ("minestrone",          "Minestrone"),
    ("miso soup",           "Miso Soup"),
    ("chicken soup",        "Chicken Soup"),
    ("beef soup",           "Beef Soup"),
    ("tomato soup",         "Tomato Soup"),
    ("vegetable soup",      "Vegetable Soup"),
    ("mushroom soup",       "Mushroom Soup"),
    ("lentil soup",         "Lentil Soup"),
    ("bean soup",           "Bean Soup"),
    # ---- Spices (compound first)
    ("garlic powder",       "Garlic Powder"),
    ("onion powder",        "Onion Powder"),
    ("chili powder",        "Chili Powder"),
    ("curry powder",        "Curry Powder"),
    ("bay leaves",          "Bay Leaves"),
    ("bay leaf",            "Bay Leaves"),
    ("cinnamon",            "Cinnamon"),
    ("paprika",             "Paprika"),
    ("cumin",               "Cumin"),
    ("oregano",             "Oregano"),
    ("basil",               "Basil"),
    ("thyme",               "Thyme"),
    ("rosemary",            "Rosemary"),
    ("cayenne",             "Cayenne"),
    ("turmeric",            "Turmeric"),
    ("ginger",              "Ginger"),
    ("nutmeg",              "Nutmeg"),
    ("allspice",            "Allspice"),
    ("saffron",             "Saffron"),
    ("vanilla",             "Vanilla"),
    # Salt varieties (compound first)
    ("himalayan pink salt", "Himalayan Pink Salt"),
    ("himalayan salt",      "Himalayan Pink Salt"),
    ("pink himalayan",      "Himalayan Pink Salt"),
    ("pink salt",           "Pink Salt"),
    ("sea salt",            "Sea Salt"),
    ("kosher salt",         "Kosher Salt"),
    ("truffle salt",        "Truffle Salt"),
    ("smoked salt",         "Smoked Salt"),
    ("black salt",          "Black Salt"),
    ("hawaiian salt",       "Hawaiian Salt"),
    ("celtic salt",         "Celtic Salt"),
    ("fleur de sel",        "Fleur de Sel"),
    ("flaky salt",          "Flaky Salt"),
    ("rock salt",           "Rock Salt"),
    ("iodized salt",        "Iodized Salt"),
    ("garlic salt",         "Garlic Salt"),
    ("onion salt",          "Onion Salt"),
    ("seasoned salt",       "Seasoned Salt"),
    ("margarita salt",      "Margarita Salt"),
    # Rubs (compound first)
    ("bbq rub",             "BBQ Rub"),
    ("barbecue rub",        "BBQ Rub"),
    ("steak rub",           "Steak Rub"),
    ("chicken rub",         "Chicken Rub"),
    ("pork rub",            "Pork Rub"),
    ("brisket rub",         "Brisket Rub"),
    ("dry rub",             "Dry Rub"),
    # Bouillon / broth / bases (compound first)
    ("bouillon cube",       "Bouillon Cubes"),
    ("bouillon",            "Bouillon"),
    ("broth base",          "Broth Base"),
    ("soup base",           "Soup Base"),
    ("demi glace",          "Demi Glace"),
    ("demi-glace",          "Demi Glace"),
    ("beef base",           "Beef Base"),
    ("chicken base",        "Chicken Base"),
    ("pork base",           "Pork Base"),
    ("turkey base",         "Turkey Base"),
    ("ham base",            "Ham Base"),
    ("clam base",           "Clam Base"),
    ("shrimp base",         "Shrimp Base"),
    ("vegetable base",      "Vegetable Base"),
    ("fish base",           "Fish Base"),
    ("stock",               "Stock"),
    # Generic salt/pepper LAST (fallback)
    ("salt",                "Salt"),
    ("pepper",              "Pepper"),
    # ---- Generic fallbacks
    ("seasoning",           "Seasoning"),
    ("oil",                 "Oil"),
    ("sauce",               "Sauce"),
    ("vinegar",             "Vinegar"),
    ("soup",                "Soup"),
    ("pasta",               "Pasta"),
    ("noodle",              "Noodles"),
]

TIERS: list[list[tuple[str, str]]] = [
    # Tier 1: oil/grain quality
    [
        ("extra virgin",    "Extra Virgin"),
        ("virgin",          "Virgin"),
        ("refined",         "Refined"),
        ("unrefined",       "Unrefined"),
        ("cold pressed",    "Cold Pressed"),
        ("expeller pressed","Expeller Pressed"),
    ],
    # Tier 2: heat level (sauces / spices)
    [
        ("extra hot",       "Extra Hot"),
        ("medium hot",      "Medium Hot"),
        ("mild",            "Mild"),
        ("medium",          "Medium"),
        ("hot",             "Hot"),
    ],
    # Tier 3: prep style / form
    [
        ("ground",          "Ground"),
        ("whole",           "Whole"),
        ("cracked",         "Cracked"),
        ("flakes",          "Flakes"),
        ("powder",          "Powder"),
        ("granulated",      "Granulated"),
    ],
]
