"""Produce family — fruit, vegetables, salad kits, herbs."""
from __future__ import annotations

FAMILY = "Produce"

SUB_FAMILY_BY_TYPE: dict[str, str] = {
    # Vegetables
    **{t: "Vegetables" for t in [
        "Potatoes", "Sweet Potatoes", "Tomatoes", "Carrots", "Onions",
        "Garlic", "Broccoli", "Cauliflower", "Cabbage", "Spinach",
        "Kale", "Lettuce", "Romaine", "Arugula", "Mixed Greens",
        "Peppers", "Bell Peppers", "Jalapeños", "Cucumbers", "Zucchini",
        "Squash", "Eggplant", "Mushrooms", "Asparagus", "Brussels Sprouts",
        "Celery", "Corn", "Peas", "Green Beans", "Beets", "Radishes",
        "Avocados", "Artichokes", "Leeks", "Scallions", "Shallots",
        "Pumpkin", "Butternut Squash", "Acorn Squash", "Bok Choy",
        "Swiss Chard", "Collard Greens", "Mustard Greens",
        "Vegetable Blend", "Stir Fry Vegetables",
    ]},
    # Fruits
    **{t: "Fruit" for t in [
        "Apples", "Bananas", "Oranges", "Grapes", "Strawberries",
        "Blueberries", "Raspberries", "Blackberries", "Cherries",
        "Pineapple", "Mango", "Watermelon", "Cantaloupe", "Honeydew",
        "Peaches", "Pears", "Plums", "Apricots", "Nectarines",
        "Lemons", "Limes", "Grapefruit", "Kiwi", "Pomegranate",
        "Papaya", "Coconut", "Dragon Fruit", "Persimmon",
        "Cranberries", "Currants", "Figs", "Dates",
        "Mixed Berries", "Tropical Fruit Mix", "Frozen Fruit",
    ]},
    # Salad
    **{t: "Salad Kits" for t in [
        "Caesar Salad Kit", "Garden Salad", "Spring Mix", "Salad Kit",
    ]},
    # Herbs
    **{t: "Fresh Herbs" for t in [
        "Fresh Basil", "Fresh Cilantro", "Fresh Parsley", "Fresh Mint",
        "Fresh Dill", "Fresh Rosemary", "Fresh Thyme", "Fresh Oregano",
        "Fresh Sage", "Fresh Chives",
    ]},
}

TYPE_KEYWORDS: list[tuple[str, str]] = [
    # ---- Compound vegetables
    ("sweet potato",        "Sweet Potatoes"),
    ("brussels sprout",     "Brussels Sprouts"),
    ("butternut squash",    "Butternut Squash"),
    ("acorn squash",        "Acorn Squash"),
    ("bok choy",            "Bok Choy"),
    ("swiss chard",         "Swiss Chard"),
    ("collard green",       "Collard Greens"),
    ("mustard green",       "Mustard Greens"),
    ("mixed green",         "Mixed Greens"),
    ("bell pepper",         "Bell Peppers"),
    ("jalapeño",            "Jalapeños"),
    ("jalapeno",            "Jalapeños"),
    ("green bean",          "Green Beans"),
    ("vegetable blend",     "Vegetable Blend"),
    ("stir fry vegetable",  "Stir Fry Vegetables"),
    # ---- Single-word vegetables
    ("potato",              "Potatoes"),
    ("tomato",              "Tomatoes"),
    ("carrot",              "Carrots"),
    ("onion",               "Onions"),
    ("garlic",              "Garlic"),
    ("broccoli",            "Broccoli"),
    ("cauliflower",         "Cauliflower"),
    ("cabbage",             "Cabbage"),
    ("spinach",             "Spinach"),
    ("kale",                "Kale"),
    ("lettuce",             "Lettuce"),
    ("romaine",             "Romaine"),
    ("arugula",             "Arugula"),
    ("cucumber",            "Cucumbers"),
    ("zucchini",            "Zucchini"),
    ("squash",              "Squash"),
    ("eggplant",            "Eggplant"),
    ("mushroom",            "Mushrooms"),
    ("asparagus",           "Asparagus"),
    ("celery",              "Celery"),
    ("corn",                "Corn"),
    ("peas",                "Peas"),
    ("beet",                "Beets"),
    ("radish",              "Radishes"),
    ("avocado",             "Avocados"),
    ("artichoke",           "Artichokes"),
    ("leek",                "Leeks"),
    ("scallion",            "Scallions"),
    ("shallot",             "Shallots"),
    ("pumpkin",             "Pumpkin"),
    ("pepper",              "Peppers"),
    # ---- Compound fruits
    ("dragon fruit",        "Dragon Fruit"),
    ("mixed berry",         "Mixed Berries"),
    ("mixed berries",       "Mixed Berries"),
    ("tropical fruit",      "Tropical Fruit Mix"),
    ("frozen fruit",        "Frozen Fruit"),
    # ---- Single-word fruits
    ("strawberry",          "Strawberries"),
    ("strawberries",        "Strawberries"),
    ("blueberry",           "Blueberries"),
    ("blueberries",         "Blueberries"),
    ("raspberry",           "Raspberries"),
    ("raspberries",         "Raspberries"),
    ("blackberry",          "Blackberries"),
    ("blackberries",        "Blackberries"),
    ("cherry",              "Cherries"),
    ("cherries",            "Cherries"),
    ("pineapple",           "Pineapple"),
    ("mango",               "Mango"),
    ("watermelon",          "Watermelon"),
    ("cantaloupe",          "Cantaloupe"),
    ("honeydew",            "Honeydew"),
    ("peach",               "Peaches"),
    ("pear",                "Pears"),
    ("plum",                "Plums"),
    ("apricot",             "Apricots"),
    ("nectarine",           "Nectarines"),
    ("lemon",               "Lemons"),
    ("lime",                "Limes"),
    ("grapefruit",          "Grapefruit"),
    ("kiwi",                "Kiwi"),
    ("pomegranate",         "Pomegranate"),
    ("papaya",              "Papaya"),
    ("coconut",             "Coconut"),
    ("persimmon",           "Persimmon"),
    ("cranberry",           "Cranberries"),
    ("cranberries",         "Cranberries"),
    ("currant",             "Currants"),
    ("fig",                 "Figs"),
    ("date",                "Dates"),
    ("apple",               "Apples"),
    ("banana",              "Bananas"),
    ("orange",              "Oranges"),
    ("grape",               "Grapes"),
    # ---- Salad kits
    ("caesar salad kit",    "Caesar Salad Kit"),
    ("garden salad",        "Garden Salad"),
    ("spring mix",          "Spring Mix"),
    ("salad kit",           "Salad Kit"),
    # ---- Herbs
    ("fresh basil",         "Fresh Basil"),
    ("fresh cilantro",      "Fresh Cilantro"),
    ("fresh parsley",       "Fresh Parsley"),
    ("fresh mint",          "Fresh Mint"),
    ("fresh dill",          "Fresh Dill"),
    ("fresh rosemary",      "Fresh Rosemary"),
    ("fresh thyme",         "Fresh Thyme"),
    ("fresh oregano",       "Fresh Oregano"),
    ("fresh sage",          "Fresh Sage"),
    ("fresh chives",        "Fresh Chives"),
]

TIERS: list[list[tuple[str, str]]] = [
    # Tier 1: form / cut
    [
        ("baby",            "Baby"),
        ("whole",           "Whole"),
        ("sliced",          "Sliced"),
        ("diced",           "Diced"),
        ("chopped",         "Chopped"),
        ("shredded",        "Shredded"),
        ("ground",          "Ground"),
        ("crushed",         "Crushed"),
        ("halved",          "Halved"),
        ("quartered",       "Quartered"),
    ],
    # Tier 2: ripeness / state
    [
        ("ripe",            "Ripe"),
        ("unripe",          "Unripe"),
        ("frozen",          "Frozen"),
        ("dried",           "Dried"),
        ("fresh",           "Fresh"),
    ],
    # Tier 3: variety
    [
        ("yellow",          "Yellow"),
        ("red",             "Red"),
        ("green",           "Green"),
        ("white",           "White"),
        ("black",           "Black"),
        ("purple",          "Purple"),
    ],
]
